### ISSUE TITLE
Unable to get MeetingId and teamsContext properties in a teams tab that has been added to a meeting

### ISSUE THREAD

**Issue by mohammadamer** [OfficeDev/TeamsFx#7953] opened 2023-03-05 14:53 UTC
**Describe the bug**
MeetingId in teamsContext is always null and almost all TeamsContext properties.

**To Reproduce**
1. Create a C# team tab app
2. Change the code a bit to retrieve current the meeting Id where the tab has been added.
3. when debugging no errors but almost all properties are null
4. See sceenshot 

**Expected behavior**
Expected behavior is to be able to retrieve the teams context properties and the meeting Id

**Screenshots**

**VS Code Extension Information (please complete the following information):**
 - OS: [e.g. Winwows]
 - IDE: Visual studio

**Additional context**
Code changes to get meeting Id

`        await base.OnAfterRenderAsync(firstRender);

        if(firstRender)
        {
            await MicrosoftTeams.InitializeAsync();
            isInTeams = await MicrosoftTeams.IsInTeams();

            if (isInTeams)
            { 
                var teamsMeeting = await MicrosoftTeams.GetTeamsContextAsync();
                if (!String.IsNullOrEmpty(teamsMeeting.MeetingId))
                    meetingId = teamsMeeting.MeetingId;
                else
                    meetingId = "";
            }
            else
            {
                errorMessage = "Not running in Microsoft Teams.";
            }

            isLoading = false;
            StateHasChanged();            
        }`

![image](https://user-images.githubusercontent.com/19314043/222967967-70addbe9-e8aa-4e71-bbf1-6083b6bdb19d.png)

**Comment by JerryYangKai** [comment] 2023-03-06 02:17
Hi @mohammadamer, I have followed your step and used your code to repro this.
The result is I can get the context including the meeting id, maybe you can use the step I provided and check if it worked.

- 1 Create a tab app project
- 2 Change the manifest file like this, it means add some properties in 'configurable tab'  
- ![image](https://user-images.githubusercontent.com/53805504/223003987-6a4f4b02-d978-47e9-8d04-e87de4e0a0c3.png)
- 3 Update the code like yours 
- 4 'Prepare Teams app dependencies' then F5
- 5 Add to a meeting
![image](https://user-images.githubusercontent.com/53805504/223004218-e561af80-ca6f-463d-8d59-4095263e149e.png)
![image](https://user-images.githubusercontent.com/53805504/223004300-c916d364-56df-4a1e-806b-de882d086a38.png)
- 6 Select the tab, in the local debug output you can find the meeting id
![image](https://user-images.githubusercontent.com/53805504/223004438-e92975c7-6658-4237-aaf8-7e1817a9b12e.png)

**Comment by mohammadamer** [comment] 2023-03-06 08:42
Hi @JerryYangKai 

You described what I exactly did but still null properties.
This is my solution package versions. Are you having the same?

```
  <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.0" />
    <PackageReference Include="Microsoft.Graph" Version="4.44.0" />
    <PackageReference Include="Microsoft.Fast.Components.FluentUI" Version="1.5.3" />
    <PackageReference Include="Microsoft.TeamsFx" Version="1.2.*" />
```

**Comment by JerryYangKai** [comment] 2023-03-06 09:51
@mohammadamer Package versions are same. The reason seems not from the project, maybe caused by account or something else, because this is not only meeting id miss, but all the context.
Could you please try this and see if it works? This is a NodeJS project, and it is our getting started in-meeting app sample.
https://github.com/OfficeDev/TeamsFx-Samples/tree/dev/hello-world-in-meeting

**Comment by mohammadamer** [comment] 2023-03-06 10:16
@JerryYangKai 
hello-world-in-meeting NodeJS  is working fine with me but I wanted to use C# and Graph .NET SDK.

**Comment by JerryYangKai** [comment] 2023-03-07 04:07
@mohammadamer  Hi, I found it is caused by the teams-js v2 breaking change. You can see more in this page
https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/using-teams-client-library?tabs=javascript%2Cmanifest-teams-toolkit#updating-to-teamsjs-version-20

The context interface has been changed like this 
![image](https://user-images.githubusercontent.com/53805504/223318136-db93d86a-eeea-458b-b161-d2b9e72130ea.png)

And in this file we still using the old one
![image](https://user-images.githubusercontent.com/53805504/223317861-85d28d56-bac5-4d67-be9a-2467a8cd3fd6.png)

I will tag this issue and we will fix it in future release. For now, I suggest you to follow the teams js new schema and change the context interface in project.

**Comment by mohammadamer** [comment] 2023-03-07 09:49
Hi @JerryYangKai 
I'm new to MS Teams development and I'm a bit confused :)
Is there an article on what exactly needs to be changed?
I see that the steps explained in the article is for VS code.

What about Visual studio?

**Comment by JerryYangKai** [comment] 2023-03-08 01:30
@mohammadamer  
We will fix it and you can get the fixed one in future release, but it needs some time.
If you want to let it quick work, I suggest follow the solution I provided and fix it by yourself. Or it doesn't matter, I will let you know our progress to help you solve it as soon as possible (like add you as reviewer of the fixed pull request).

**Comment by JerryYangKai** [comment] 2023-03-08 01:30
@mohammadamer  
We will fix it and you can get the fixed one in future release, but it needs some time.
If you want to let it quick work, I suggest follow the solution I provided and fix it by yourself. Or it doesn't matter, I will let you know our progress to help you solve it as soon as possible (like add you as reviewer of the fixed pull request).

**Comment by JerryYangKai** [comment] 2023-03-08 02:44
@mohammadamer  Here's the example
`public class TeamsContext
{
    public MeetingInfo Meeting { get; set; }
}

public class MeetingInfo
{
    public string Id { get; set; }
}`
Change to this and you will get the meeting id.

**Comment by JerryYangKai** [comment] 2023-03-09 01:49
Tag it as bug and I will close the issue when the fix merged.

**Comment by JerryYangKai** [comment] 2023-03-15 04:17
Fixed in https://github.com/OfficeDev/TeamsFx/pull/8038

**Closed by JerryYangKai** 2023-03-15 04:17 UTC
Labels: bug, TA:Compute, .NET
