### ISSUE TITLE
bug report: AppStudioPlugin.DeveloperPortalAPIFailed

### ISSUE THREAD

**Issue by mizginstlm** [OfficeDev/TeamsFx#6978] opened 2022-11-24 12:19 UTC
API call to Developer Portal failed: Error, Request failed with status code 422, API name: create-app, X-Correlation-ID: 5fe7d18c-8cd6-4478-abdb-05d8e75e952f. This may come from some intermittent service error. Please wait for a few minutes and retry the current step. data: "Value cannot be <REDACTED: user-file-path> name: accessToken"

stack:
DeveloperPortalAPIFailed: API call to Developer Portal failed: Error, Request failed with status code 422, API name: create-app, X-Correlation-ID: 5fe7d18c-8cd6-4478-abdb-05d8e75e952f. This may come from some intermittent service error. Please wait for a few minutes and retry the current step. data: "Value cannot be <REDACTED: user-file-path> name: accessToken"
	at AppStudioResultFactory.SystemError (<REDACTED: user-file-path>:2:7657360)
	at wrapException (<REDACTED: user-file-path>:2:7626256)
	at Object.importApp (<REDACTED: user-file-path>:2:7629559)
	at process.processTicksAndRejections (node:<REDACTED: user-file-path>:96:5)
	at async Object.createTeamsApp (<REDACTED: user-file-path>:2:7609468)
	at async AppManifest.provision (<REDACTED: user-file-path>:2:7582333)
	at async AppManifest.<anonymous> (<REDACTED: user-file-path>:2:6957183)
	at async TeamsfxCore.provision (<REDACTED: user-file-path>:2:6511322)
	at async TeamsfxCore.<anonymous> (<REDACTED: user-file-path>:2:6957183)
	at async FxCore.provisionResourcesOld (<REDACTED: user-file-path>:2:7943430)
	at async FxCore.<anonymous> (<REDACTED: user-file-path>:2:8080524)
	at async exports.ProjectSettingsWriterMW (<REDACTED: user-file-path>:2:8135874)
	at async exports.ContextInjectorMW (<REDACTED: user-file-path>:2:8069319)
	at async FxCore.<anonymous> (<REDACTED: user-file-path>:2:8075982)
	at async exports.ProjectSettingsLoaderMW (<REDACTED: user-file-path>:2:8134511)
	at async exports.ProjectVersionCheckerMW (<REDACTED: user-file-path>:2:8139330)
	at async exports.AadManifestMigrationMW (<REDACTED: user-file-path>:2:8048999)
	at async exports.ProjectConsolidateMW (<REDACTED: user-file-path>:2:8069031)
	at async exports.ProjectMigratorMW (<REDACTED: user-file-path>:2:8118007)
	at async exports.ConcurrentLockerMW (<REDACTED: user-file-path>:2:8051543)
	at async exports.ErrorHandlerMW (<REDACTED: user-file-path>:2:8082459)

**Comment by Githamza** [comment] 2023-03-07 18:40
any updates ? I have a similar issue ?

```
√ Teams app manifest is resolved and app package is saved in /Users/hamzahaddad/TeamsApps/newtabfromscrach/rhapp/build/appPackage/appPackage.local.zip

× DeveloperPortalAPIFailed: API call to Developer Portal failed: Error, Request failed with status code 422, API name: create-app, X-Correlation-ID: c5d96f9c-9284-4290-872f-5ae5e6d3b923. This may come from some intermittent service error. Please wait for a few minutes and retry the current step. data: "Error mapping types.\r\n\r\nMapping types:\r\nApplicationManifest -> AppDefinition\r\nAppStudio.API.Models.ApplicationManifest -> AppStudio.API.Models.AppDefinition\r\n\r\nType Map configuration:\r\nApplicationManifest -> AppDefinition\r\nAppStudio.API.Models.ApplicationManifest -> AppStudio.API.Models.AppDefinition\r\n\r\nDestination Member:\r\nMeetingExtensionDefinition\r\n"

Visit https://aka.ms/teamsfx-debug-prepare-manifest-task to learn more about 'Build and upload Teams manifest' task.
```

**Comment by nliu-ms** [comment] 2023-03-09 06:44
Hey @Githamza , can you please provide the "meetingExtensionDefinition" section in your manifest? And if you do not use this section, please remove it and try again to see if it works. Thank you.

**Comment by nliu-ms** [comment] 2023-03-10 03:19
Got it @Githamza , I can reproduce the error, I will report it to Teams Developer Portal team, it might be a bug from server side. Sorry for the inconvenience.

**Comment by nliu-ms** [comment] 2023-03-13 01:49
Hey @Githamza , Teams Developer Portal team has deployed a hotfix. Can you please try again and let me know if it works for you now? Thank you!

**Comment by Githamza** [comment] 2023-03-13 09:28
I don't get the error anymore , but the feature is not working yet. anonymous users don't see the app when it's shared on meeting stage . Is the fix concerning the toolkit error or also the feature that's not working ?

<img width="713" alt="image" src="https://user-images.githubusercontent.com/11578288/224660756-16bf244f-c55a-46b8-a12c-1cbf82ac1893.png">

**Comment by nliu-ms** [comment] 2023-03-16 05:15
Hey @Githamza , the fix was concerning the Toolkit error. I will reach out to Teams Developer Portal team for more information.

**Comment by nliu-ms** [comment] 2023-03-31 01:44
Hey @Githamza, I've got the response from corresponding team. This is currently expected as some dependency was rolled back earlier this month, and the ETA for the fix is the **end of April**. I will keep you updated, sorry for the inconvenience!

**Comment by Githamza** [comment] 2023-03-31 07:48
What is going to be fixed by the end of April ? 
The toolkit compilation error or the apps running with anonymous user feature ?

**Comment by nliu-ms** [comment] 2023-04-03 01:28
@Githamza , sorry for the ambiguity. The anonymous user in meeting stage feature will be fixed by the end of April.

**Comment by Githamza** [comment] 2023-04-29 08:56
Any updates ? When the bug will be fixed ? It's important for my business to work well

**Comment by nliu-ms** [comment] 2023-05-04 02:58
Hey @Githamza , I got the updates from corresponding team that the scenario "anonymous user in meeting stage" is not fully supported due to a dependency on React on Web experience, which is not fully rolled out. I'm checking with them about the ETA. Will get back to you ASAP.

**Comment by nliu-ms** [comment] 2023-05-06 02:07
Hey @Githamza , sorry for the late reply. I checked with the team who implements the scenario of supporting anonymous user in meeting. Unfortunately, they gave me a bad news that this scenario is not supported as planned, it is currently blocked on a dependency and there is no ETA for the re-rollout plan. I will follow up with them and get back to you when I get any updates, sorry for the inconvenience.

**Comment by Githamza** [comment] 2023-05-06 03:43
Oh ! That a really bad news ! It's killing my whole business idea ! I'm upset .. so much time working on that. So sad the team is not able to solve that

**Comment by Githamza** [comment] 2023-05-06 06:07
Will this feature be maintained and fixed later in futur at least ? Or It will be canceled ?

**Comment by nliu-ms** [comment] 2023-05-06 07:43
@Githamza , as far as I know the feature will be maintained and fixed later, won't be cancelled. I'm asking them if they have channels to communicate with users. If so, I will let you know and you can get latest update from them.

**Comment by Githamza** [comment] 2023-05-06 08:39
Thank you , 
I need visibility to decide how should I implement my features and communicate to clients . 
When you say later , that does mean what ? 1 month , 6 months ?

**Comment by nliu-ms** [comment] 2023-05-11 02:54
Hey @Githamza , I still get no ETA from Meeting Extensibility team. But they will find a public forum for communicating with users. I will let you know once I get updated, and you can use the forum to get more visibility from them. Thanks!

**Comment by Githamza** [comment] 2023-05-14 20:36
Thank you . I'll wait for you updates

**Comment by nliu-ms** [comment] 2023-06-01 01:47
Hey @Githamza , I got the response from Meeting Extensibility team. You can use public forums listed below to ask questions about Teams. Please remember to use correct tag, it will make the question to the correct team. Sorry for the inconvenience! Hope you can get detailed answers there.
https://learn.microsoft.com/en-us/microsoftteams/platform/feedback#developer-community-forums

**Comment by nliu-ms** [comment] 2023-07-26 07:19
Close this issue as it's delivered to Meeting Extensibility team.

**Closed by nliu-ms** 2023-07-26 07:19 UTC
Labels: upstream
