### ISSUE TITLE
Action file/updateEnv in lifecycle configureApp is not found

### ISSUE THREAD

**Issue by sockese** [OfficeDev/TeamsFx#7327] opened 2022-12-23 09:28 UTC
**Describe the bug**

**To Reproduce**
1. I followed the Microsoft's tutorial to create a Teams app until step 3 - substep 2 https://learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-blazorupdate?tabs=vs&tutorial-step=3

But the the "Prepare Teams App Dependencies" command failed with the following error:

[ConfigManager]Executing lifecycle registerApp
[ConfigManager]Trying to resolve actions for lifecycle registerApp
[ConfigManager]Action aadApp/create found for lifecycle registerApp
[ConfigManager]Action teamsApp/create found for lifecycle registerApp
[ConfigManager]Executing action aadApp/create in lifecycle registerApp
Executing action aadApp/create
Environment variable AAD_APP_CLIENT_ID already exist, skipping new AAD app creation step.
Environment variable SECRET_AAD_APP_CLIENT_SECRET already exist, skipping new AAD app creation step.
Action aadApp/create executed successfully
[ConfigManager]Action aadApp/create in lifecycle registerApp succeeded with output {"AAD_APP_CLIENT_ID":"ee2c4041-607f-4806-96bc-fcecd0f883a1","SECRET_AAD_APP_CLIENT_SECRET":"******","AAD_APP_OBJECT_ID":"b24bfb2c-3a21-4de2-9d56-7575b8efc01d","AAD_APP_TENANT_ID":"75c07e3d-f4d0-4dd8-a1e0-578137ed90d4","AAD_APP_OAUTH_AUTHORITY":"https://login.microsoftonline.com/75c07e3d-f4d0-4dd8-a1e0-578137ed90d4","AAD_APP_OAUTH_AUTHORITY_HOST":"https://login.microsoftonline.com"}
[ConfigManager]Executing action teamsApp/create in lifecycle registerApp
[ConfigManager]Action teamsApp/create in lifecycle registerApp succeeded with output {"TEAMS_APP_ID":"4ebf710e-7196-48df-a6d1-1381ef31417f","TEAMS_APP_TENANT_ID":"75c07e3d-f4d0-4dd8-a1e0-578137ed90d4"}
[ConfigManager]Finished Executing lifecycle registerApp. Result: {"AAD_APP_CLIENT_ID":"ee2c4041-607f-4806-96bc-fcecd0f883a1","SECRET_AAD_APP_CLIENT_SECRET":"******","AAD_APP_OBJECT_ID":"b24bfb2c-3a21-4de2-9d56-7575b8efc01d","AAD_APP_TENANT_ID":"75c07e3d-f4d0-4dd8-a1e0-578137ed90d4","AAD_APP_OAUTH_AUTHORITY":"https://login.microsoftonline.com/75c07e3d-f4d0-4dd8-a1e0-578137ed90d4","AAD_APP_OAUTH_AUTHORITY_HOST":"https://login.microsoftonline.com","TEAMS_APP_ID":"4ebf710e-7196-48df-a6d1-1381ef31417f","TEAMS_APP_TENANT_ID":"75c07e3d-f4d0-4dd8-a1e0-578137ed90d4"}
[ConfigManager]Executing lifecycle configureApp
[ConfigManager]Trying to resolve actions for lifecycle configureApp
[ConfigManager]Action file/updateEnv in lifecycle configureApp is not found
[ConfigManager]Failed to Execute lifecycle configureApp. DriverNotFoundError:Driver file/updateEnv not found for step 
{
  "errorType": "UserError",
  "source": "ConfigManager",
  "name": "DriverNotFoundError",
  "message": "Driver file/updateEnv not found for step ",
  "stack": "DriverNotFoundError: Driver file/updateEnv not found for step \n    at Lifecycle.getDrivers (C:\\snapshot\\TeamsFx\\packages\\server\\lib\\index.js)\n    at Lifecycle.executeImpl (C:\\snapshot\\TeamsFx\\packages\\server\\lib\\index.js)\n    at Lifecycle.execute (C:\\snapshot\\TeamsFx\\packages\\server\\lib\\index.js)\n    at Coordinator.provision (C:\\snapshot\\TeamsFx\\packages\\server\\lib\\index.js)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async Coordinator.<anonymous> (C:\\snapshot\\TeamsFx\\packages\\server\\lib\\index.js)\n    at async FxCore.provisionResourcesNew (C:\\snapshot\\TeamsFx\\packages\\server\\lib\\index.js)\n    at async FxCore.<anonymous> (C:\\snapshot\\TeamsFx\\packages\\server\\lib\\index.js)\n    at async FxCore.<anonymous> (C:\\snapshot\\TeamsFx\\packages\\server\\lib\\index.js)\n    at async Object.envLoaderMWImpl (C:\\snapshot\\TeamsFx\\packages\\server\\lib\\index.js)",
  "innerError": null,
  "userData": null,
  "timestamp": "2022-12-23T09:18:54.369Z",
  "displayMessage": "Driver file/updateEnv not found for step ",
  "helpLink": "https://aka.ms/teamsfx-actions/action-not-found",
  "issueLink": null
}

**Expected behavior**
I expect this command to complete without error, as stated in the tutorial

**VS Code Extension Information (please complete the following information):**
 - OS: Windows 11
 - Version VS Code 17.5.0 - Preview 2.0

**Comment by kuojianlu** [comment] 2022-12-26 08:58
I can reproduce this issue. It seems that 17.5 Preview 2 uses the latest template but old FxCore. Besides `file/updateEnv`, `file/updateAppSettings` and `teamsApp/zipAppPackage` are also not found.

The workaround is to use the old action names: `file/updateEnv` -> `env/generate`, `file/updateAppSettings` -> `appsettings/generate`, `teamsApp/zipAppPackage` -> `teamsApp/createAppPackage`.

Assign to @chagong because it is not due to `file/updateEnv` action. FYI: @adashen

**Comment by hund030** [comment] 2022-12-27 03:19
@sockese
When creating a new project, Teams Toolkit downloads latest templates from [GitHub releases](https://github.com/OfficeDev/TeamsFx/releases/tag/templates%401.5.0) by default. 
We have introduced breaking changes in the latest template without upgrade the major version, which caused this issue.

This issue should be fixed in VS 17.5 Preview 3. For 17.5 Preview 2, you can work around by the steps:
1. Set environment variable TEAMSFX_TEMPLATE_PRERELEASE="fallback" and restart your Visual Studio.
2. Create a new project. Teams Toolkit failed to find templates from GitHub because the prerelease tag is invalid so that use a fallback bit.
3. Now "Prepare Teams App Dependencies" command should succeed.

**Comment by grumpykiwi** [comment] 2023-01-03 22:28
I get the following when trying to run an existing Teams project is VS 2022 Preview 2.

1>------ Deploy started: Project: TeamStatus2023, Configuration: Debug Any CPU ------
1>Start Teams Toolkit pre-debug task...
1>Teams App Project not found in this solution.
========== Deploy: 0 succeeded, 1 failed, 0 skipped ==========
========== Deploy started at 4:27 PM and took 00.065 seconds ==========

Is this related to the issue above? Will setting the env var fix it ?

**Comment by blackchoey** [comment] 2023-01-05 07:56
@grumpykiwi Is your project a production purpose project or you use this project to explore Teams app development and Teams Toolkit's feature?

If it's a production purpose project, we recommend you using stable version Visual Studio for development.

We enabled some preview features in VS 2022 Preview 2 to help you better develop your Teams app, which requires some folder structure change. And the preview features are subject to change. You can create a new project using VS 2022 Preview 2 to explore these new features. If you want to explore the new features with your existing project, please let us know and we will share further information about how to upgrade your project with our tooling.

**Comment by grumpykiwi** [comment] 2023-01-05 08:12
It’s a production app. It’s pretty stable so doesn’t require a lot of maintenance. Which version of visual studio will I need to use to make changes? Having said that I am very interested in exploring the new features with a fork of the current project. I like to play with the new features to see what I can use to improve the overall experience for my users. It’s a tab based app and would like to be able to run it inside outlook as an option for users

Mark Nash
Senior Software Engineer        [cid:PC_42x23_fbb4e57e-65d2-4c41-b09e-ffa9f4a3c468.png]

PartnerComm, Inc.
Winner of 86 IABC Gold Quills
2022 Large Agency of the Year
2304 W Interstate 20, Suite 250
Arlington, TX 76017
        [cid:pcomm25+_471933a4-f842-490b-84d4-910cf0397a29.png]

Office: (817) 465-9277
***@***.***
www.partnercomm.net<http://www.partnercomm.net>





This e-mail transmission may contain confidential information or may be otherwise legally privileged. If you are not the intended recipient you are hereby notified that any use, disclosure, copying, forwarding, or distribution of any of the information contained in or attached to this message is STRICTLY PROHIBITED.

________________________________

________________________________

**Comment by blackchoey** [comment] 2023-01-18 05:47
@grumpykiwi Thanks for your patience. The Visual Studio 2022 17.5 Preview 3.0 will be released soon. You can use this version to open your project, which can auto upgrade your project when you execute any Teams Toolkit command.

Please be aware this is only for preview purpose so do not use it for production purpose and make proper backups for your projects. Feel free to open new issues to share your feedbacks when you try the new version.

**Comment by grumpykiwi** [comment] 2023-01-19 18:01
Thanks. VS picked up the update last night and I was able to build and publish ok.


Mark Nash
Senior Software Engineer        [cid:PC_42x23_fbb4e57e-65d2-4c41-b09e-ffa9f4a3c468.png]

PartnerComm, Inc.
Winner of 86 IABC Gold Quills
2022 Large Agency of the Year
2304 W Interstate 20, Suite 250
Arlington, TX 76017
        [cid:pcomm25+_471933a4-f842-490b-84d4-910cf0397a29.png]

Office: (817) 465-9277
***@***.***
www.partnercomm.net<http://www.partnercomm.net>





This e-mail transmission may contain confidential information or may be otherwise legally privileged. If you are not the intended recipient you are hereby notified that any use, disclosure, copying, forwarding, or distribution of any of the information contained in or attached to this message is STRICTLY PROHIBITED.

________________________________

**Closed** 2023-01-29 19:01 UTC
Labels: investigating, needs more info, TA:E2E, no recent activity, needs attention
