### ISSUE TITLE
Identify current theme not working for one route. 

### ISSUE THREAD

**Issue by shabbir-dhangot** [OfficeDev/TeamsFx#7050] opened 2022-12-01 10:38 UTC
I am working on the MS Teams app where I have a page in which I want to identify current MS Teams theme (default, dark or high contrast). This page is having code where it loads website I want into iframe. 

Route config

    <Route path="/websitetab/:Url" component={WebsiteTab} />

I am creating Website tab with user of following url https://localhost:53000/index.html?#/websitetab/encodedURL which load website in the iframe. This loading my component where I have code to identify current theme. Code as below.

    import type { ReactElement } from "react";
    import { useEffect, useState } from "react";
    import { useParams } from "react-router-dom";
    import { useTeamsFx } from "@microsoft/teamsfx-react";

    const THEME_MAP = new Map<string, string>([
        ["default", "normal_theme"],
        ["dark", "dark_theme"],
        ["contrast", "contrast_theme"]
    ]);
    type TParams = { Url: string };
    const THEME_PARAMETER_NAME = "ui-theme";

    export default function WebsiteTab(): ReactElement {
        const params = useParams<TParams>();
        const { themeString } = useTeamsFx();
        const [url, setUrl] = useState("");

        useEffect(() => {
            const nextUrl = new URL(decodeURIComponent(params.Url));
            const theme = THEME_MAP.get(themeString);
            if(theme)
                nextUrl.searchParams.set(THEME_PARAMETER_NAME, theme);
            setUrl(nextUrl.toString());
        }, [themeString, params.Url]);

        return (
            <div>
                <iframe
                    id="frame"
                    title="Application Frame"
                    src={url}
                    width="100%"
                    height="100%"
                    style={{
                        border: "none"
                    }}
                />
            </div>
        );
    }    

**Expected behavior**
It should identify theme.

**Comment by huimiu** [comment] 2022-12-05 13:14
Hi @shabbir-dhangot, thanks for contacting us. I tried it with the code you provided above, and I would like to share my steps. 

1.  I added the `https://www.bing.com/` encoded link to the back of `/websitetab`, the final link looks like this: `/websitetab/https%3A%2F%2Fwww.bing.com%2F`.

2. Modified the `contentUrl` and `websiteUrl` value in the `manifest.template.json` file.

3. Local debug and checked the `url` value.
![image](https://user-images.githubusercontent.com/107838226/205644263-b95f969d-1c88-45af-b321-a1c752c6d033.png)


4. Changed the theme of teams, checked the `url` value.
![image](https://user-images.githubusercontent.com/107838226/205644459-524a8318-e942-46b2-bc73-80293ce1124b.png)

5. All as expected.


You didn't provide the code about the `manifest.template.json` file, maybe you can check if it is configured with the `websitetab` url, something like this:

```json
...
"staticTabs": [
        {
            "entityId": "index0",
            "name": "Personal Tab",
            "contentUrl": "{{{state.fx-resource-frontend-hosting.endpoint}}}{{{state.fx-resource-frontend-hosting.indexPath}}}/websitetab/https%3A%2F%2Fwww.bing.com%2F",
            "websiteUrl": "{{{state.fx-resource-frontend-hosting.endpoint}}}{{{state.fx-resource-frontend-hosting.indexPath}}}/websitetab/https%3A%2F%2Fwww.bing.com%2F",
            "scopes": [
                "personal"
            ]
        }
    ],
...
```

If you still have problems, please feel free to contact us.

**Comment by shabbir-dhangot** [comment] 2022-12-06 04:40
Hi Huimui,

Above flow you explained  is of the normal tab. Here theme I am getting it correctly. 

    <Router>
        <Route exact path="/">
              <Redirect to="/tab" />
         </Route>
          {loading ? (
              <Loader style={{ margin: 100 }} />
          ) : (
              <>
                  <Route exact path="/tab" component={Tab} />
                  <Switch>
                      <Route path="/websitetab/:Url" component={WebsiteTab} />
                  </Switch>
              </>
        )}
    </Router>

As I explained I have a route which I am using it to load website. So, we have functionality "Share as a Tab to Microsoft Teams" where we share our website to particular user by creating website tab. See below screenshot for reference. 

![image](https://user-images.githubusercontent.com/8267282/205815588-74de0187-9c0d-4777-a8ef-5bdbcade6923.png)

Now this tab is having URL https://localhost:53000/index.html?#/websitetab/encodedURL loading my component. I want to change theme according to the MSTeams theme which I am not able identify on this specific component. 

I hope it's clear now

**Comment by huimiu** [comment] 2022-12-11 14:37
Hi @shabbir-dhangot, sorry for the late reply, I was recently busy with a release.

Yeah, I got it. Currently, the value of `themeString` in `useTeamsFx` only reloads the correct value when the page is reloaded. I think in your application scenario, you can try the `useTeams` method.

```typescript
import { useTeams } from "@microsoft/teamsfx-react";
```

```typescript
export declare function useTeams(options?: {
    initialTheme?: string;
    setThemeHandler?: (theme?: string) => void;
}): [
    {
        inTeams?: boolean;
        fullScreen?: boolean;
        theme: ThemePrepared;
        themeString: string;
        context?: app.Context;
    },
    {
        setTheme: (theme: string | undefined) => void;
    }
];
```

The `setThemeHandler` parameter can receive a method that will be called when the theme of teams is changed. So maybe you can achieve your needs this way.

```typescript
...
export default function WebsiteTab(): ReactElement {
    const params = useParams<TParams>();
    const [themeString, setThemeString] = useState("default");
    const {} = useTeams({
      initialTheme: "default",
      setThemeHandler: (theme?: string) => {
        setThemeString(theme ?? "default");
      },
    })[0];
    const [url, setUrl] = useState("");

    useEffect(() => {
        const nextUrl = new URL(decodeURIComponent(params.Url));
        const theme = THEME_MAP.get(themeString);
        if(theme)
            nextUrl.searchParams.set(THEME_PARAMETER_NAME, theme);
        setUrl(nextUrl.toString());
    }, [themeString, params.Url]);


    return (
        <div>
            <iframe
                id="frame"
                title="Application Frame"
                src={url}
                width="100%"
                height="100%"
                style={{
                    border: "none"
                }}
            />
        </div>
    );
}
... 
```

I hope it can help you solve the problem, thanks.

**Comment by shabbir-dhangot** [comment] 2022-12-12 05:48
Hi Huimiu, 

I have tried this approach as well earlier. 

    const { inTeams } = useTeams({
        initialTheme: "default",
        setThemeHandler: (theme?: string) => {
            console.log("inside", theme);
            setThemeString(theme ?? "default");
        }
    })[0];

This returns inTeams as **false** and themeString is still **default** even though we are in dark theme.

**Comment by huimiu** [comment] 2022-12-12 11:43
Hi @shabbir-dhangot, I would like to share [my project](https://github.com/huimiu/issue-debug) which can get the values of `inTeams` and `themeString` correctly. Maybe you can see how it is different from your implementation. You can submit a PR with your non-working implementation to this repo or share your project if convenient, so that I can better find and solve your problem. Thanks.

I'm thinking maybe your component is not running in Teams, if `inTeams` is false, `teamsfx-react` related methods will not work properly.

**Comment by shabbir-dhangot** [comment] 2022-12-12 12:35
Thank you @huimiu, I will check this and see if it's working for me or not

**Comment by shabbir-dhangot** [comment] 2022-12-15 14:12
Hi Huimiu,

I appreciate time you have given to create project. Unfortunately your code its not working what use case I am telling it to you. Attached screenshot below.

![image](https://user-images.githubusercontent.com/8267282/207882087-e80fe377-3d11-49ab-b69f-39387038f578.png)

To reproduce same follow below steps.

1. Run application
2. Goto one to one chat
3. Click on Add (+) button and select Website.
4. Give any name and URL as https://localhost:53000/index.html?#/websitetab/https%3A%2F%2Fwww.bing.com%2F
5. You can see that its returning normal_theme instead of dark_theme as shown in above screenshot.

**Comment by huimiu** [comment] 2022-12-23 04:53
Hi @shabbir-dhangot, sorry for the late reply. According to your steps and description, I have reproduced your problem. 

**Adding Website** will load your website in iframe. In iframe, `useTeams` can't recognize if it is running in Teams or something else. Because `useTeams` is based on @microsoft/teams-js, the [app instance](https://github.com/OfficeDev/microsoft-teams-library-js/blob/main/packages/teams-js/src/public/app.ts#L536) of teams-js can't be initialized in iframe. 

So I'm sorry to tell you that the current theme may not be recognized in the iframe, maybe you should consider other ways, such as developing a native tab app for a Teams channel or group.

**Comment by huimiu** [comment] 2022-12-29 01:36
@shabbir-dhangot Thank you for contacting us, close this issue first, if you have other questions feel free to contact us again.

**Closed by huimiu** 2022-12-29 01:36 UTC
Labels: *as-designed, TA:Compute
