### ISSUE TITLE
bug report: AppStudioPlugin.LocalAppIdUpdateFailed

### ISSUE THREAD

**Issue by pjirsa** [OfficeDev/TeamsFx#3257] opened 2021-12-07 15:55 UTC
Failed to update local app id in app studio due to 503: Cannot get the app definition with app ID a198bbd8-4668-4877-974c-0a1207866190, due to Error: Request failed with status code 503.

stack:
LocalAppIdUpdateFailed: Failed to update local app id in app studio due to 503: Cannot get the app definition with app ID a198bbd8-4668-4877-974c-0a1207866190, due to Error: Request failed with status code 503.
    at Function.SystemError (<REDACTED: user-file-path>:2:5685440)
    at AppStudioPluginImpl.updateApp (<REDACTED: user-file-path>:2:5677020)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (<REDACTED: user-file-path>:93:5)
    at AppStudioPluginImpl.getAppDefinitionAndUpdate (<REDACTED: user-file-path>:2:5635006)
    at AppStudioPluginImpl.postLocalDebug (<REDACTED: user-file-path>:2:5658725)
    at AppStudioPlugin.postLocalDebug (<REDACTED: user-file-path>:2:5625818)
    at async Promise.all (index 4)
    at Object.executeConcurrently (<REDACTED: user-file-path>:2:6324825)
    at TeamsAppSolution.doLocalDebug (<REDACTED: user-file-path>:2:6367876)
    at TeamsAppSolution.localDebug (<REDACTED: user-file-path>:2:6365144)
    at FxCore.localDebug (<REDACTED: user-file-path>:2:5051195)
    at FxCore.exports.LocalSettingsWriterMW (<REDACTED: user-file-path>:2:5099787)
    at FxCore.<anonymous> (<REDACTED: user-file-path>:2:5093342)
    at FxCore.exports.ProjectSettingsWriterMW (<REDACTED: user-file-path>:2:5146912)
    at FxCore.exports.ContextInjectorMW (<REDACTED: user-file-path>:2:5084111)
    at FxCore.exports.QuestionModelMW (<REDACTED: user-file-path>:2:5158412)
    at FxCore.<anonymous> (<REDACTED: user-file-path>:2:5159311)
    at FxCore.exports.LocalSettingsLoaderMW (<REDACTED: user-file-path>:2:5099328)
    at FxCore.<anonymous> (<REDACTED: user-file-path>:2:5090572)
    at FxCore.exports.ProjectSettingsLoaderMW (<REDACTED: user-file-path>:2:5145704)
    at FxCore.exports.ProjectUpgraderMW (<REDACTED: user-file-path>:2:5154768)
    at FxCore.exports.ProjectMigratorMW (<REDACTED: user-file-path>:2:5142761)
    at FxCore.<anonymous> (<REDACTED: user-file-path>:2:5160049)
    at FxCore.exports.ConcurrentLockerMW (<REDACTED: user-file-path>:2:5083379)
    at FxCore.exports.ErrorHandlerMW (<REDACTED: user-file-path>:2:5095626)

**Comment by pjirsa** [comment] 2021-12-07 15:57
Getting 503 errors when debugging Teams app locally. It appears to be failing when loading sourcemaps from https://local.teams.office.com.

**Comment by pjirsa** [comment] 2021-12-07 17:08
example from debug console:
```
Could not read source map for https://statics.teams.cdn.office.net/teams-modular-packages/hashed-assets/33786-42ffd7bff58c4554.js: Unexpected 503 response from https://local.teams.office.com/sourcemaps/hashed-assets/33786-42ffd7bff58c4554.js.map: getaddrinfo ENOENT local.teams.office.com
```

**Comment by nliu-ms** [comment] 2021-12-08 06:06
Thank you so much for reporting it. We have noticed this bug yesterday and the root cause comes from the server side. The server had a change and caused some unexpected behaviour. We have reported it to the team.

Sorry for the inconvenience! I will update the latest news here.

**Comment by nliu-ms** [comment] 2021-12-14 02:28
The server side should be stable now, will close this issue. Sorry for the inconvenience!

**Closed by nliu-ms** 2021-12-14 02:28 UTC
Labels: investigating, TA:E2E

**Comment by LeHailender** [comment] 2022-02-21 12:36
I'm not sure if this is related, but I still get a lot of such warning messages when.  When trying to debug an app locally?

`WARNING: Processing source-maps of [https://statics.teams.cdn.office.net/teams-modular-packages/hashed-assets/13355-2139021a4ac7d52d.js]() took longer than 987.7089000000005 ms so we continued execution without waiting for all the breakpoints for the script to be set.Could not read source map for [https://statics.teams.cdn.office.net/teams-modular-packages/hashed-assets/auth-163a48c03eb036a9.js](): Unexpected 503 response from [https://local.teams.office.com/sourcemaps/hashed-assets/auth-163a48c03eb036a9.js.map](): getaddrinfo ENOTFOUND local.teams.office.comWARNING: Processing source-maps of [https://statics.teams.cdn.office.net/teams-modular-packages/hashed-assets/13355-2139021a4ac7d52d.js]() took longer than 987.7089000000005 ms so we continued execution without waiting for all the breakpoints for the script to be set.Could not read source map for [https://statics.teams.cdn.office.net/teams-modular-packages/hashed-assets/auth-163a48c03eb036a9.js](): Unexpected 503 response from [https://local.teams.office.com/sourcemaps/hashed-assets/auth-163a48c03eb036a9.js.map](): getaddrinfo ENOTFOUND local.teams.office.com`

**Comment by amansani15** [comment] 2022-05-30 12:55
Same here, I am still getting these messages too

**Comment by kuojianlu** [comment] 2022-05-31 07:32
@LeHailender @amansani15 These messages have nothing to do with this issue, see https://github.com/OfficeDev/TeamsFx/issues/5201 for more details.
