### ISSUE TITLE
UI doesn't display correctly when VS Code set to German language

### ISSUE THREAD

**Issue by therealjohn** [OfficeDev/TeamsFx#8850] opened 2023-05-30 14:17 UTC
**Describe the bug**
When VS Code is configured to display in German language, the buttons and UI for Teams Toolkit doesn't display correctly. Notice the `command:fx` strings, etc.

**To Reproduce**
1. Install Teams Toolkit in VS Code
2. Set the display language to Deutsch (German)
3. VS Code will need to restart
4. Select the Teams Toolkit menu item when it restarts

**Expected behavior**
See valid UI and buttons

**Screenshots**
![image](https://github.com/OfficeDev/TeamsFx/assets/1501196/9aed7603-f9c9-4a95-b8b0-109c532df184)

**VS Code Extension Information (please complete the following information):**
 - OS: Windows

**Comment by HuihuiWu-Microsoft** [comment] 2023-06-25 02:03
Hi @therealjohn, bug has been filed and waiting for localization team to fix.

**Comment by csigs** [comment] 2023-06-28 23:52
Thank you for your feedback. We are currently reviewing it (reference 861626).

**Comment by v-mholloway** [comment] 2023-06-29 10:01
@therealjohn could you provide the version of VS Code you are using as we cannot reproduce the issue here.

**Comment by csigs** [comment] 2023-06-30 01:09
The issue has been fixed in localization platform that the fix should be exported to production repo and will take effect in next release! (Reference id: 861626)

**Closed by csigs** 2023-06-30 01:09 UTC
Labels: bug, TA:E2E, needs attention
