### ISSUE TITLE
Unable to login with SSO in bot. No auth window was open under debug mode

### ISSUE THREAD

**Issue by taoh** [OfficeDev/TeamsFx#4930] opened 2022-05-06 10:55 UTC
**Describe the bug**
When using TeamsFx bot sso login feature under debug mode, the bot displays the SSO login prompt, but nothing happens when clicking 'continue' button, so user cannot login.

**To Reproduce**
1. Type 'login' to invoke sso login command
2. Click on 'continue' button (see screenshots below'
3. No auth window is open. There is an error in Dev Tools console:

```
BotSsoRequestContainer: Bot SSO Sign In token auth request failed for bot 28:dcc8d520-6bc5-4cf8-8e26-a8035fd40ff9
```

**Expected behavior**
An auth window opens to allow use to login.

**Screenshots**
![image](https://user-images.githubusercontent.com/647539/167117919-fb68056d-8f7c-499f-ae38-e513adbbc170.png)

**VS Code Extension Information (please complete the following information):**
 - OS: MacOS
 - Version: 1.66.2

**TeamsFx 
- Version: ^0.2.0

**Additional context**

The code to create the bot is the same as sample. We tried many times removing and installing the Teams app to no avail. 

```javascript
    loadConfiguration();
    this.addDialog(
      new TeamsBotSsoPrompt(TEAMS_SSO_PROMPT_ID, {
        scopes: this.requiredScopes,
        endOnInvalidMessage: true,
      })
    );
```

**Comment by blackchoey** [comment] 2022-05-07 05:21
Hi @taoh this is a known issue and we're working to fix this problem. Can you try following workaround and let us know whether it works?
1. Hard reload (ctrl+F5) your Teams web client, and see whether the login works.
2. If 1) does not work, stop local debugging and debug again.
3. If 2) does not work, logout the Teams account and clear browser caches (data), then try to local debug again.
4. If 3) does not work, delete `.fx/states/state.local.json` or `.fx/configs/localSettings.json` and try to local debug again. Please kindly notice this will **delete your current resources for local debugging** and create new resources for local debugging.

By the way, the code you referenced is an old one. You could refer this sample to understand how to build apps with Bot SSO feature (this sample still uses `TeamsBotSsoPrompt`): https://github.com/OfficeDev/TeamsFx-Samples/tree/dev/bot-sso

**Comment by taoh** [comment] 2022-05-10 06:10
@blackchoey Thank you for your reply. We have tried all 3 options above to no avail. This is a blocking issue for us, and in my opinion, an urgent fix is needed because it completely blocks SSO scenarios in bot. We have spent couple of days on this and cannot submit our apps due to this problem.

In my understanding, the newer sample doesn't solve this problem. Please advise otherwise.

We're considering switching away from TeamsFx which is a pity.

**Comment by MuyangAmigo** [comment] 2022-05-16 07:21
@taoh We are working with the Teams team to resolve this issue. Thanks for reporting it to us.

**Comment by blackchoey** [comment] 2022-05-18 07:22
One reason for this issue: Teams may loads old app definition when installing the app. If the valid domain in old app definition is out of date, Teams will refuse to open the login page since the domain of login page does not match the valid domain declared in Teams app manifest.

Here's one workaround for above issue:
1. After installed your teams app to Teams, log out current user
2. Login again

Above steps ensure latest app is loaded. You should be able to open login page when Bot SSO requires you to login.

**Comment by blackchoey** [comment] 2023-01-18 06:04
The related fix has been applied to M365 developer tenant. I'm going to close this issue.
If you have further questions, feel free to open new issues.

**Closed by blackchoey** 2023-01-18 06:04 UTC
Labels: upstream, TA:Auth

**Comment by himawan-r** [comment] 2023-09-13 05:38
Hi @blackchoey i have the same issue as this one, no window is opened. i tried to open the dev tools when i trigger the command and i saw this error i wonder what it is and if it is the cause 
![Screen Shot 2023-09-13 at 12 05 05](https://github.com/OfficeDev/TeamsFx/assets/8610314/a1946064-224c-4047-bfc9-f397778c536a)
![Screen Shot 2023-09-13 at 12 04 46](https://github.com/OfficeDev/TeamsFx/assets/8610314/8979d9da-0b72-46c4-8534-df9b5ee7d2bf)

https://teams.microsoft.com/api/chatsvc/apac/v1/agents/28:256d2663-3d03-483b-b690-e93215141254/invoke
its my bot id 256d2663-3d03-483b-b690-e93215141254, i guess it try to do something but failed

**Comment by blackchoey** [comment] 2023-09-15 01:35
The request failure is expected because the user needs to login and consent required permission. Teams will only show the login button when this request fails.

Can you check is there any error logs in dev tool's console tab? In the meanwhile, it would be great to share the repro steps so we can try to repro.

**Comment by Krumelur** [comment] 2023-09-15 10:37
Seeing the same behaviour here with Teams client apps. The browser based Teams works and will open the window as expected, the apps won't.

**Comment by blackchoey** [comment] 2023-09-18 05:37
> Seeing the same behaviour here with Teams client apps. The browser based Teams works and will open the window as expected, the apps won't.

One possible reason is Teams desktop client is using the old Teams app manifest, where the `valid domain` in the manifest does not match the latest dev tunnel url used for local debugging. Teams will not open the login window for you in this case. Can you try to manually upload your `appPackage.local.zip` to Teams desktop client when this happens and see whether it works?

**Comment by Krumelur** [comment] 2023-09-18 07:57
Thanks @blackchoey - that's exactly what I tried: sideloading the Teams app package. It refuses to open the login window. What should the section with the valid domains in manifest.json look like? This is what it currently is, it has only my app service domain in it:

```
"validDomains": [
    "zzzzz-xxxxxxxxx-dev.azurewebsites.net"
],
```
