### ISSUE TITLE
Deployment fails in my production Subscription which is connected to Partner Center but works in my Visual Studio Subscription

### ISSUE THREAD

**Issue by bemokraig** [OfficeDev/TeamsFx#6233] opened 2022-09-28 00:07 UTC
How do I troubleshoot this error?  
[core] start task:deployArtifactsV2 
[core] success to acquire lock for task deployArtifactsV2  on: C:\Users\KraigRury\source\repos\Bemo-Dev\BemoAssistWebApp\.fx
[core:env] success to get questions for target environment.
[dev] is selected as the target environment to deployArtifactsV2
[core] success to get questions for deployArtifactsV2
[Teams Toolkit] Selected plugins to deploy: ["fx-resource-frontend-hosting","fx-resource-aad-app-for-teams"]
[Teams Toolkit] Deployment start.
Running fx-resource-frontend-hosting concurrently
Running fx-resource-aad-app-for-teams concurrently
[fx-resource-frontend-hosting] Deploying.
[Teams Toolkit] Execute Task summary----------------------------
fx-resource-frontend-hosting-deploy......................... [failed]
fx-resource-aad-app-for-teams-deploy........................ [ok]
[Teams Toolkit] Task overall result.........................[failed]
fail to deploy 'BemoAssistWebApp' to the cloud!
[core] persist env state: C:\Users\KraigRury\source\repos\Bemo-Dev\BemoAssistWebApp\.fx\states\state.dev.json
[core] persist project setting file: C:\Users\KraigRury\source\repos\Bemo-Dev\BemoAssistWebApp\.fx\configs\projectSettings.json
[core] lock released on C:\Users\KraigRury\source\repos\Bemo-Dev\BemoAssistWebApp\.fx
[core] finish task:deployArtifactsV2 , time: 3736 ms
{
  "errorType": "SystemError",
  "source": "FE",
  "name": "UnhandledError",
  "message": "Unhandled error.",
  "stack": "UnhandledError: Unhandled error.\n    at Function.SystemError (C:\\snapshot\\TeamsFx\\packages\\server\\lib\\index.js)\n    at FrontendPlugin.runWithErrorHandling (C:\\snapshot\\TeamsFx\\packages\\server\\lib\\index.js)\n    at async Object.deployAdapter (C:\\snapshot\\TeamsFx\\packages\\server\\lib\\index.js)\n    at async FrontendPluginV2.deploy (C:\\snapshot\\TeamsFx\\packages\\server\\lib\\index.js)\n    at async Promise.all (index 0)\n    at async Object.executeConcurrently (C:\\snapshot\\TeamsFx\\packages\\server\\lib\\index.js)\n    at async TeamsAppSolutionV2.deploy (C:\\snapshot\\TeamsFx\\packages\\server\\lib\\index.js)\n    at async FxCore.deployArtifactsV2 (C:\\snapshot\\TeamsFx\\packages\\server\\lib\\index.js)\n    at async FxCore.<anonymous> (C:\\snapshot\\TeamsFx\\packages\\server\\lib\\index.js)\n    at async FxCore.<anonymous> (C:\\snapshot\\TeamsFx\\packages\\server\\lib\\index.js)",
  "innerError": {
    "errno": -4058,
    "code": "ENOENT",
    "syscall": "open",
    "path": "C:\\Users\\kraig\\source\\repos\\WebApps\\BemoAssistWebApp\\BemoAssistWebApp.csproj"
  },
  "userData": null,
  "timestamp": "2022-09-28T00:04:34.451Z",
  "displayMessage": "Unhandled error.",
  "helpLink": null,

**Comment by bemokraig** [comment] 2022-09-29 19:21
I spun up a VM and installed VS2022 17.3.5 and it fails out of the box.

**Comment by hund030** [comment] 2022-09-30 02:10
The error message show that it failed to open the file `C:\Users\kraig\source\repos\WebApps\BemoAssistWebApp\BemoAssistWebApp.csproj`. 
@bemokraig Could you help if the file exists?
If the path is wrong, you can go `.fx/configs/projectSettings.json` to find the path and replace it with your exact path.

**Comment by bemokraig** [comment] 2022-09-30 02:21
Yes the path is correct.  Sometimes but not always I've seen the tools update the path automatically.  I don't think this path is the actual not-found issue.  I looked at that a lot but I think it just extra detail, not the error.

"C:\Users\KraigRury\source\repos\WebApps\BemoAssistWebApp\BemoAssistWebApp.csproj"

On the other hand it is a very bad design to hard code a path into code that gets checked into devops and cloned somewhere else.  I also think the .ignore file ignores too much to be useful.

The same code works on one machine but not another, Windows 10 but not 11?  Sometimes I think it is a token issue as I have 600 partner tenants (CSP).

I'm doing a lot of development with Teams right now, if you want a good test subject I'm it.

Thanks for the reply.

Kraig


Kraig Rury | Principal Software Development Manager
Microsoft Alumni
|425.616.0802

**Comment by hund030** [comment] 2022-09-30 03:01
@bemokraig Thanks for your information. The hard code path indeed is a problem. We are fixing it in the latest bit, which will be released soon.
While I really think the filepath is the root cause. The path you provide seems different from the one in your error message. 
C:\Users\ **kraig** \source\repos\WebApps\BemoAssistWebApp\BemoAssistWebApp.csproj
C:\Users\ **KraigRury** \source\repos\WebApps\BemoAssistWebApp\BemoAssistWebApp.csproj

I just try remove my project to another folder and get exactly same error messages. And it is resolved after I update the path in projectSetting.json. Could you have a try?

As for the gitignore, what do you think it should not ignore? Any suggestion will be very helpful.

**Comment by bemokraig** [comment] 2022-09-30 03:41
I hate to say it but you are right, I would look at the last elements of the path to see they matched but did not look closely enough.  To me that path was just information not the missing file itself, it looked right.  Ah well.

As for gitignore, maybe I am influenced by the issue above.  If you can check in, check out on another box (fix the path) and have everything work (including userdata) so that you can just fix a bug and deploy then all is good.  At one point I thought that not all the files I needed were being checked in but I will have to verify that and reply.

The error messages are not clear, I had another issue where VS was trying to get a token from the wront tenant and that was another case of "an error occurred we got null" message.

I very much appreciate your timely response it has saved me considerable time.

Kraig



Kraig Rury | Principal Software Development Manager
Microsoft Alumni
|425.616.0802

**Comment by hund030** [comment] 2022-09-30 04:29
@bemokraig Gald to see your issue been resolved. For the token issue, I suggest you file another GitHub issue to track it, so that we can loop in correct person.

**Comment by LockTar** [comment] 2022-10-14 06:48
This path issue is really a problem when working in a Team. Hopefully this is resolved ASAP.
Took me hours to find the problem.
Thanks

**Comment by hund030** [comment] 2022-10-17 09:12
This issue is resolved in [VS 17.4 preview 3](https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes-preview)

**Comment by adashen** [comment] 2022-10-18 06:24
close as the issue is resolved

**Closed by adashen** 2022-10-18 06:24 UTC
Labels: investigating, TA:Compute
