### ISSUE TITLE
Unable to provisioned a second cloud environment

### ISSUE THREAD

**Issue by FxWxP** [OfficeDev/TeamsFx#3637] opened 2022-01-12 11:26 UTC
**Describe the bug**
We have a production environment. When I want to provision a second (demo) environment, it fails on provisioning.

**To Reproduce**
Start with an user without any cloud environments
1. In the environment section in the Teams Toolkit in vscode click on the create environment, let's call this one "prod"
2. In the deployment section run "Provision in the cloud" for the "prod" environment
3. Deploy to the cloud for the "prod" section, we only deploy our "Tab Front-end" and "Azure Function" resources
4. In the environment section in the Teams Toolkit in vscode click on the create environment, let's call this one "demo"
5. In the deployment section run "Provision in the cloud" for the "demo" environment
6. See error, for some reason it is trying to create a number of resources with the same ids as in the first resource group.

**Expected behavior**
That the provisioning for the second environment goes without any problems.

**Screenshots**
![image](https://user-images.githubusercontent.com/94601125/149131657-f81ce1f5-44d3-4b65-b6a8-8842aacb71ef.png)

**VS Code Extension Information (please complete the following information):**
 - OS: Windows 10
 - Version 3.2.0

**CLI Information (please complete the following information):**
 - OS: Windows 10
 - Version Where do I find this?

**Comment by dooriya** [comment] 2022-01-13 06:38
Hi @FxWxP,

Thank you for reporting this issue!
From the repro steps you provided, looks like the resource name is conflict between these two environments. Could you kindly check the `resourceBaseName` property in both `.fx\configs\azure.parameters.prod.json` and `.fx\configs\azure.parameters.demo.json`? The base name for different are supposed to be different as I showed below:

![image](https://user-images.githubusercontent.com/10163840/149278088-0b74c700-6704-4aa0-9b6b-c1dd7032e571.png)

![image](https://user-images.githubusercontent.com/10163840/149277945-a0b1352d-4e7f-4ea1-af86-7b48c5cffb72.png)

**Comment by FxWxP** [comment] 2022-01-13 09:55
I checked and the resource base name is different.
All the ids below however are similar between the two files and it seems this is what the error is about, because those ids are mentioned in the error message.
It does create some of the element in the resource group however.
![image](https://user-images.githubusercontent.com/94601125/149306866-d22bb93c-0997-474e-87eb-0136f9017b0c.png)
The bottom two service plans do not have the environment name in their name.

As in the error in the screenshot above in the issue. The ids in the section "simpleAuthProvision" there are the same as "simpleAuthServerFarmsName" and "simpleAuthWebAppName" in the "azure.parameters.demo.json". 
The "functionProvision" section has the id from "functionServerfarmsName", "functionStorageName" and "functionWebappName".
And the "frontendHostingProvision" has the id from "frontendHostingStorageName".

**Comment by dooriya** [comment] 2022-01-14 03:12
As you can see in my screenshot, the toolkit will append a random string (e.g. d98047, 9c98a3) in the `resourceBaseName` to avoid resource name conflict when provision. 

For example, prod environment:
![image](https://user-images.githubusercontent.com/10163840/149443973-41e788bf-7198-417d-86be-a555bbb9a190.png)

demo environment:
![image](https://user-images.githubusercontent.com/10163840/149444299-48f29f9e-b547-4489-ba60-978721a97ffa.png)

As you said "_it is trying to create a number of resources **with the same ids** as in the first resource group_" in the issue description, but "**the resource base name is different**" in the `azure.parameters.<env>.json`. So what are the conflict resources (website & storageAccount) name since the resource base name is different? Or did you ever manually config some other provision parameters in the `azure.parameters.<env>.json`?  For example, if you manually configure a `simpleAuthWebAppName` in your  `azure.parameters.<env>.json`, then you need to ensure the value of the `simpleAuthWebAppName` should be different in those two files.

To understand the issue better and to troubleshoot further, could you please share your `azure.parameters.demo.json` and `azure.parameters.prod.json` to us?

**Comment by FxWxP** [comment] 2022-01-17 10:35
@adashen for me, it has a different base name the `azure.parameters.<env>.json`. It just does not seem to add a the environment to all the resources it creates in the resource group. As you can see in my last screenshot, the two last elements, the app service plans do not have the environment name `demo` added to their name.
I haven't changed anything by hand in the files, I also do not need any customization. 
See them in this zip file:
[environments.zip](https://github.com/OfficeDev/TeamsFx/files/7881122/environments.zip)

**Comment by dooriya** [comment] 2022-01-19 07:00
Hi @FxWxP, sorry for the belated circling back.

## Root cause
The root cause of the resource provision conflict is due to copy some azure parameters (e.g.` frontendHostStorageName`) from the original "dev" environment, which is generated by project upgrade from v2 to v3 to reuse the original resource you provisioned before. And **these parameters will overwrite the `resourceBaseName` when doing Azure provision**.

## Workaround
To unblock your development, you can remove the following highlight parameters in `azure.parameters.demo.json` and `azure.parameters.prod.json`  to allow toolkit to use the `resourceBaseName` to provision resource.
![image](https://user-images.githubusercontent.com/10163840/150077649-57f4693e-ce7a-4188-a0da-64acbb9e8600.png).

## Avoid this issue in new environment
And if you want to **add more environment in this project**, you can create from demo/prod environment that fixed by removing those parameters to avoid copy conflict azure parameters.
![image](https://user-images.githubusercontent.com/10163840/150079388-6a681d3c-0a8d-4ca6-b025-a0eb85571d03.png)

**Comment by FxWxP** [comment] 2022-01-27 10:46
Sorry for the late response, I got overloaded with different stuff...
The workaround on top seems to be working good. 
Although I do not see the copy step when creating or provisioning, make that is not in my version? (v3.2.0)

**Comment by adashen** [comment] 2022-01-28 06:27
close as it is resolved

**Closed by adashen** 2022-01-28 06:27 UTC
Labels: investigating, TA:Infra, needs attention
