### ISSUE TITLE
bug report: Solution.SetupLocalDebugSettingsError: Cannot set property 'AuthServiceEndpoint' of undefined

### ISSUE THREAD

**Issue by danwatford** [OfficeDev/TeamsFx#3689] opened 2022-01-17 11:20 UTC
Hello,

Following upgrade of the vscode Teams Toolkit extension to v3.2.0 I am no longer able to launch debugging for an existing Personal Tab project based on an SPFx webpart.

Running vscode on Windows 10, project hosted in WSL:Ubuntu-20.04.

Attempts to launch the Teams workbench (Chrome) debug configuration fail with the following error printed in the Teams Toolkit output window:

stack:
TypeError: Cannot set property 'AuthServiceEndpoint' of undefined
    at Object.setupLocalDebugSettings (<REDACTED: user-file-path>:2:6448463)
    at TeamsAppSolutionV2.provisionLocalResource (<REDACTED: user-file-path>:2:6672465)
    at processTicksAndRejections (<REDACTED: user-file-path>:93:5)
    at FxCore.localDebugV2 (<REDACTED: user-file-path>:2:5194458)
    at FxCore.exports.LocalSettingsWriterMW (<REDACTED: user-file-path>:2:5246496)
    at FxCore.<anonymous> (<REDACTED: user-file-path>:2:5239050)
    at FxCore.exports.ProjectSettingsWriterMW (<REDACTED: user-file-path>:2:5294995)
    at FxCore.exports.ContextInjectorMW (<REDACTED: user-file-path>:2:5227455)
    at FxCore.exports.QuestionModelMW (<REDACTED: user-file-path>:2:5301867)
    at FxCore.SolutionLoaderMW (<REDACTED: user-file-path>:2:5311058)
    at FxCore.exports.LocalSettingsLoaderMW (<REDACTED: user-file-path>:2:5246076)
    at FxCore.<anonymous> (<REDACTED: user-file-path>:2:5234466)
    at FxCore.exports.ProjectSettingsLoaderMW (<REDACTED: user-file-path>:2:5291989)
    at FxCore.exports.ProjectMigratorMW (<REDACTED: user-file-path>:2:5289082)
    at FxCore.<anonymous> (<REDACTED: user-file-path>:2:5312348)
    at FxCore.exports.ConcurrentLockerMW (<REDACTED: user-file-path>:2:5226413)
    at FxCore.exports.ErrorHandlerMW (<REDACTED: user-file-path>:2:5242213)

Downgrading the Teams Toolkit extension to v3.1.1 restores debug functionality.

**Comment by kuojianlu** [comment] 2022-01-18 04:12
This is a bug caused by wrong `includeSimpleAuth` check https://github.com/OfficeDev/TeamsFx/blob/main/packages/fx-core/src/common/local/projectSettingsHelper.ts#L38, already fixed in dev branch by @swatDong in #3646.

**Comment by swatDong** [comment] 2022-01-18 07:04
@danwatford - thanks for reporting this. Indeed this is a code bug and already fixed in dev branch, and the fix will be included in coming release.

By the way, besides downgrading to v3.1.1, another workaround could be manually adjusting `.fx/configs/localSettings.json` - adding a workaround section `"auth":{}`, e.g.,
``` json
{
    "teamsApp": {
        "tenantId": "{your-existing-tenantid}",
        "teamsAppId": "{your-existing-teamsappid}"
    },
    "auth": {} // add this section as workaround
}
```

Just a workaround for v3.2.0. Feel free to leave comments. Thanks!

**Comment by danwatford** [comment] 2022-01-18 07:38
Thank you, @swatDong. 

I had previously removed the auth property from localSettings.json, thinking it to be optional and not needed for SPFx based projects. My mistake!

Adding the property back in to localSettings.json allows local debug to work again.

**Comment by adashen** [comment] 2022-02-14 02:49
close as the issue is solved

**Closed by adashen** 2022-02-14 02:49 UTC
Labels: bug, TA:Infra
