### ISSUE TITLE
Application Name is used in package.json which creates confusing warnings

### ISSUE THREAD

**Issue by therealjohn** [OfficeDev/TeamsFx#9179] opened 2023-06-29 14:59 UTC
**Describe the bug**
When creating a new project, I'm prompted to enter an Application Name which is used multiple places like the manifest.json, package.json, etc. 

The values I can enter create invalid package.json `name` values. 

Consider an app name like "TestMyApp2". This results in `"name": "TestMyApp2"` in package.json, which is not a valid value. 

**Expected behavior**
No warnings on a newly created project.

**Screenshots**
![image](https://github.com/OfficeDev/TeamsFx/assets/1501196/20322782-9db7-40f5-bd2b-449cfbc79da8)

**Additional context**
Can we resolve this by simply lowercasing the app name when using the value in `package.json`? i.e. it would be `"testmyapp2"` which is valid and produces no warnings.

**Comment by jayzhang** [comment] 2023-07-10 02:48
@therealjohn:  the issue is under progress, thanks

**Comment by hund030** [comment] 2023-07-11 08:28
This issue will be resolved in next release.

**Closed** 2023-10-09 03:17 UTC
Labels: TA:Compute, TA:E2E
