### ISSUE TITLE
bug report: AppStudioPlugin.LocalAppIdCreateFailed

### ISSUE THREAD

**Issue by ronenziporen** [OfficeDev/TeamsFx#5612] opened 2022-07-24 11:58 UTC
Failed to create local debug Teams app in Developer Portal, due to API call to Developer Portal failed: Error, Request failed with status code 422, API name: create-app, X-Correlation-ID: undefined. This may come from some intermittent service error. Please wait for a few minutes and retry the current step. data: "VS30063: You are not authorized to access https://domoreexp.visualstudio.com."

stack:
LocalAppIdCreateFailed: Failed to create local debug Teams app in Developer Portal, due to API call to Developer Portal failed: Error, Request failed with status code 422, API name: create-app, X-Correlation-ID: undefined. This may come from some intermittent service error. Please wait for a few minutes and retry the current step. data: "VS30063: You are not authorized to access https://domoreexp.visualstudio.com."
	at Function.SystemError (<REDACTED: user-file-path>:2:6121825)
	at AppStudioPluginImpl.createApp (<REDACTED: user-file-path>:2:6111515)
	at processTicksAndRejections (node:<REDACTED: user-file-path>:96:5)
	at async AppStudioPluginImpl.updateApp (<REDACTED: user-file-path>:2:6112286)
	at async AppStudioPluginImpl.getAppDefinitionAndUpdate (<REDACTED: user-file-path>:2:6074869)
	at async AppStudioPluginImpl.postLocalDebug (<REDACTED: user-file-path>:2:6097786)
	at async AppStudioPlugin.postLocalDebug (<REDACTED: user-file-path>:2:6053876)
	at async Object.configureLocalResourceAdapter (<REDACTED: user-file-path>:2:6783510)
	at async AppStudioPluginV2.configureLocalResource (<REDACTED: user-file-path>:2:6136599)
	at async Promise.all (index 3)
	at async Object.executeConcurrently (<REDACTED: user-file-path>:2:7105814)
	at async TeamsAppSolutionV2.provisionLocalResource (<REDACTED: user-file-path>:2:7167241)
	at async FxCore.localDebugV2 (<REDACTED: user-file-path>:2:5243121)
	at async FxCore.<anonymous> (<REDACTED: user-file-path>:2:5377403)
	at async FxCore.exports.ProjectSettingsWriterMW (<REDACTED: user-file-path>:2:5429129)
	at async FxCore.exports.ContextInjectorMW (<REDACTED: user-file-path>:2:5365393)
	at async FxCore.exports.QuestionModelMW (<REDACTED: user-file-path>:2:5439817)
	at async FxCore.SolutionLoaderMW (<REDACTED: user-file-path>:2:5454331)
	at async FxCore.<anonymous> (<REDACTED: user-file-path>:2:5372743)
	at async FxCore.exports.ProjectSettingsLoaderMW (<REDACTED: user-file-path>:2:5427689)
	at async FxCore.exports.ProjectVersionCheckerMW (<REDACTED: user-file-path>:2:5432189)
	at async FxCore.exports.AadManifestMigrationMW (<REDACTED: user-file-path>:2:5345195)
	at async FxCore.exports.ProjectConsolidateMW (<REDACTED: user-file-path>:2:5365105)
	at async FxCore.exports.ProjectMigratorMW (<REDACTED: user-file-path>:2:5424225)
	at async FxCore.exports.ConcurrentLockerMW (<REDACTED: user-file-path>:2:5347654)
	at async FxCore.exports.ErrorHandlerMW (<REDACTED: user-file-path>:2:5380847)

**Comment by nliu-ms** [comment] 2022-07-25 01:49
Thanks @ronenziporen ! I'm trying to figure out the root cause, this issue is duplicate with https://github.com/OfficeDev/TeamsFx/issues/5610, so will close this one.

**Closed by nliu-ms** 2022-07-25 01:49 UTC
