### ISSUE TITLE
bug report: SPFx.SPFxScaffoldError

### ISSUE THREAD

**Issue by binfouzan** [OfficeDev/TeamsFx#4600] opened 2022-04-10 08:26 UTC
Exec command: "yo @<REDACTED: user-file-path> --skip-install true --component-type webpart --component-name TL --framework react --solution-name TimeAndLabor --environment spo --skip-feature-deployment true --is-domain-isolated false" timeout, 120000 ms

stack:
SPFxScaffoldError: Exec command: "yo @<REDACTED: user-file-path> --skip-install true --component-type webpart --component-name TL --framework react --solution-name TimeAndLabor --environment spo --skip-feature-deployment true --is-domain-isolated false" timeout, 120000 ms
    at Object.ScaffoldError (<REDACTED: user-file-path>:2:6481412)
    at SPFxPluginImpl.postScaffold (<REDACTED: user-file-path>:2:6501266)
    at SpfxPlugin.runWithErrorHandling (<REDACTED: user-file-path>:2:6488168)
    at SpfxPlugin.postScaffold (<REDACTED: user-file-path>:2:6487396)
    at Object.scaffoldSourceCodeAdapter (<REDACTED: user-file-path>:2:6607383)
    at SpfxPluginV2.scaffoldSourceCode (<REDACTED: user-file-path>:2:6524327)
    at TeamsAppSolutionV2.scaffoldSourceCode (<REDACTED: user-file-path>:2:6979727)
    at FxCore.createProjectV2 (<REDACTED: user-file-path>:2:5129245)
    at FxCore.<anonymous> (<REDACTED: user-file-path>:2:5250167)
    at FxCore.exports.ProjectSettingsWriterMW (<REDACTED: user-file-path>:2:5304764)
    at FxCore.exports.ContextInjectorMW (<REDACTED: user-file-path>:2:5238494)
    at FxCore.exports.QuestionModelMW (<REDACTED: user-file-path>:2:5310976)
    at FxCore.exports.ErrorHandlerMW (<REDACTED: user-file-path>:2:5253291)

**Comment by HuihuiWu-Microsoft** [comment] 2022-04-13 05:52
Hi @binfouzan, it timed out to execute the 'yo @microsoft/sharepoint' command to scaffold spfx project from the error stack. The timeout is set to be 120s and it takes less than 10s for most of cases on my side. 
Can you help confirm whether it's reproducible on your side?

**Comment by binfouzan** [comment] 2022-04-14 08:15
hi @HuihuiWu-Microsoft, I found out that I have spfx 1.12 and teamsfx installed globally,  I had to install both.
after that, I was able to scaffold the spfx project but when I run it, it give me an error "something went wrong"

I am using osx, I had to downgrade to teams tool kit 3.6.1

**Comment by HuihuiWu-Microsoft** [comment] 2022-04-14 09:35
> hi @HuihuiWu-Microsoft, I found out that I have spfx 1.12 and teamsfx installed globally, I had to uninstall both. after that, I was able to scaffold the spfx project but when I run it, it give me an error "something went wrong"
> 
> I am using osx, I had to downgrade to teams tool kit 3.6.1

Teams Toolkit will not install spfx globally, it will be installed under HOME/.fx locally and use locally installed version(spfx v1.14.0) for scaffolding. So it doesn't matter what the global version is. Could you give more details about the error "something went wrong"?

**Comment by binfouzan** [comment] 2022-04-17 07:51
I am receiving this error know:

Error Loading Debug manifests
Error loading debug script.Ensure the server is running and the "debugeManifestsFile" parameter URL is correct.

Error: Script error for: 
https://localhost:4321/temp/manifests.js 
http://requirejs.org/docs/errors.html#scripterror

**Comment by HuihuiWu-Microsoft** [comment] 2022-04-18 01:39
> 



> I am receiving this error know:
> 
> Error Loading Debug manifests Error loading debug script.Ensure the server is running and the "debugeManifestsFile" parameter URL is correct.
> 
> Error: Script error for: https://localhost:4321/temp/manifests.js http://requirejs.org/docs/errors.html#scripterror

@binfouzan This error should happen when local debugging. So you've scaffolded spfx project successfully, right?

For this error, did you meet the issue while debugging hosted workbench? Please check whether gulp serve runs successfully. It would be better if you can attach a screenshot.

**Comment by binfouzan** [comment] 2022-04-18 11:38
yes, I scaffolded spfx project.
no, I meet the issue while debugging teams workbench

**Comment by HuihuiWu-Microsoft** [comment] 2022-04-19 02:45
> debugging teams wor

Can you help check whether gulp serve is running successfully while you do Teams workbench debugging? Is this issue reproducible?

**Comment by binfouzan** [comment] 2022-04-20 07:47
i am attaching a screen shot
<img width="1272" alt="gulp" src="https://user-images.githubusercontent.com/48059509/164177497-ba0b909e-173e-4ff6-93ed-548ec771a6e4.png">

**Comment by HuihuiWu-Microsoft** [comment] 2022-04-21 02:32
Hi @binfouzan, I'd like to confirm with you which Teams Toolkit version you're using to scaffold this project (You said you have to downgrade to v3.6.1 to scaffold) and which version you're using to do debugging?

**Comment by binfouzan** [comment] 2022-04-21 06:07
hi @HuihuiWu-Microsoft 
I upgraded again to 3.7.0 so i can follow up with you
<img width="640" alt="teamkitversipn" src="https://user-images.githubusercontent.com/48059509/164385497-fdf21c8a-6989-4854-a450-98481b76f003.png">

**Comment by binfouzan** [comment] 2022-04-21 07:47
Hi @HuihuiWu-Microsoft 
I found a workaround to do debugging on the host workbench. i  opened a new tab and load https://localhost:4321/temp/manifests.js manually
, and I can see the sample web part

<img width="1092" alt="hosted workbench" src="https://user-images.githubusercontent.com/48059509/164405130-c66d0ae2-9d6a-48de-858f-5ed4c1e6ef5f.png">

**Comment by HuihuiWu-Microsoft** [comment] 2022-04-21 09:05
Hi @binfouzan , I'm trying to summarize the issues you have met: 
For hosted workbench debugging:
1. The following error should be due to unsuccessfully launch of gulp task, pls make sure gulp serve is running successfully and the localhost:4321 is hosted correctly:
![image](https://user-images.githubusercontent.com/73154171/164419393-68d66938-3fd1-4798-87d4-8a034916c663.png)
2. The following operation shouldn't be done manually, you can do debugging via vscode debug tab and gulp will be installed automatically 
when I run gulp in the project directory:
% pwd
/Users/xxxxxx/source/MSTeams/HelloWorld/SPFx
% gulp --tasks
zsh: command not found: gulp
% gulp trust-dev-cert
zsh: command not found: gulp
3. Supported npm version for SPFx v1.14.0 is v6.x. Not sure if the 'Failed to load debug manifests' error is due to that but I suggest you to use correct version and try again.
For Teams workbench debugging,  please  also use correct npm version and try again.

**Comment by binfouzan** [comment] 2022-04-21 11:23
Hi @HuihuiWu-Microsoft 
i was able to get it to work with the following steps : 
1. create a new project 
2. run and debuge with Teams Workbench (will fail because of glup issue)
3. open an new tab in the browser and load https://localhost:4321/temp/manifests.js manually
4. reload teams tab on the browser 
5. the webpart load fine in teams 

i only need to load the manifest file once.

**Comment by HuihuiWu-Microsoft** [comment] 2022-04-22 02:12
Hi @binfouzan , I'll close this issue since you get it working now. Suggest you to use officially supported versions to avoid any unexpected issues.

**Closed** 2022-04-22 02:18 UTC
Labels: investigating, TA:E2E, needs attention
