### ISSUE TITLE
OOTB tab project "React with Fluent UI" contains flicker/flash when loading in dark &high contrast mode

### ISSUE THREAD

**Issue by andrewconnell** [OfficeDev/TeamsFx#10076] opened 2023-10-03 19:24 UTC
**Describe the bug**
When using the OOTB project type "React with Fluent UI" in VSCode & the TTK v5.2 VSC extension, when the client has the dark theme set, navigating to a tab shows a flash of white before changing to dark mode. This isn't present when the theme is set in light mode. 

The initial flash shouldn't be there.

**To Reproduce**
1. Create a new tab project using the template **React with Fluent UI** & **TypeScript
1. Start debugging
1. Once app is installed in MSTEAMS, change theme to dark, and navigate back and forth to the tab

**Expected behavior**
There's no quick flash of "white" or light color... the tab should start dark when the project is created.

**Screenshots**
See the following video: 
<div>
    <a href="https://www.loom.com/share/90418a36f1234a7cbf02b2994db2a16c">
      <p>GH - OfficeDev/TeamsFx Issue#10076 - Watch Video</p>
    </a>
    <a href="https://www.loom.com/share/90418a36f1234a7cbf02b2994db2a16c">
      <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/90418a36f1234a7cbf02b2994db2a16c-with-play.gif">
    </a>
  </div>

**VS Code Extension Information (please complete the following information):**
 - OS: macOS
 - Version v5.2

n/a

**Comment by hund030** [comment] 2023-10-07 07:34
Thanks for you feedback. The tab app needs to invoke teams-js SDK to get current theme from Teams client, which takes some time. That is why you will find the page flash before the SDK loads correct theme from Teams client.

```
const { loading, theme, themeString, teamsUserCredential } = useTeamsUserCredential({
```

The problem is that the `useTeamsUserCredential` hooks set `loading` state to false before it successfully loads current theme. Current behavior is:
dark background -> **loading indicator in light background -> tab page in light theme** -> tab page in dark theme
![ezgif-4-ee66096972](https://github.com/OfficeDev/TeamsFx/assets/26134943/56b10e45-4c78-48d7-bd3e-f8f10c63c3f2)
While I expect it should be:
dark background -> **loading indicator in light background** -> tab page in dark theme
@yiqing-zhao Could you help follow up this issue?

To get the perfect experience: dark background -> loading indicator in dark -> tab page in dark theme, it's recommended to show a native indicator.
Find more details from this document for more details: https://learn.microsoft.com/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?tabs=teamsjs-v2#show-a-native-loading-indicator

**Comment by hund030** [comment] 2023-10-19 08:28
This issue is mitigated by https://github.com/OfficeDev/TeamsFx/pull/10147. When the change is released, the behavior should be:
![Animation](https://github.com/OfficeDev/TeamsFx/assets/26134943/0fd54138-96c0-4cbf-9dee-7c2adc01f06a)

For an optimal user experience with no flashing, it is recommended that you use the native loading indicator in your tab app.
https://learn.microsoft.com/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?tabs=teamsjs-v2#show-a-native-loading-indicator

**Comment by hund030** [comment] 2024-02-19 02:20
I'm closing this since we have mitigated the issue and there is no feedback. Feel free to reopen it if you have further questions.

**Closed by hund030** 2024-02-19 02:20 UTC
Labels: TA:Compute
