### ISSUE TITLE
bug report: unknown.Error

### ISSUE THREAD

**Issue by lovethakker02** [OfficeDev/TeamsFx#5431] opened 2022-07-01 05:07 UTC
connect ETIMEDOUT 13.107.136.9:443

stack:
Error: connect ETIMEDOUT 13.107.136.9:443
	at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16)
	at TCPConnectWrap.callbackTrampoline (node:<REDACTED: user-file-path>:130:17)

**Comment by adashen** [comment] 2022-07-04 06:24
Hi @lovethakker02 Thanks for reporting the issue. Can you help to provide the reproduce steps with more detail info?
Thanks~

**Comment by lovethakker02** [comment] 2022-07-05 05:47
I am learning to build Teams app using below tutorial 

https://docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?tabs=vscode%2Cviscode

When I tried local debug I got this error. after running below command multiple time, the issue was resolved.
npm install

**Comment by lovethakker02** [comment] 2022-07-18 06:56
Hi. I have recently started learning the Teams app development and I face the issue in my first set up. If I face it repeatedly I will update it here. I don't face this issue with SPFx development on my machine.

**Comment by HuihuiWu-Microsoft** [comment] 2022-07-18 08:54
Thanks @lovethakker02, this looks like an issue from npm install instead of Team Toolkit. Please help check whether you have it repeatedly or not and feel free to update here.

**Comment by ichivers** [comment] 2022-07-20 08:35
I often get stuck on this when debuggiung:
(4/5) Checking and installing NPM packages for tab app (react-based) ...
Using a Mac / Visual Studio Code.  Sometimes running npm install and restarting Code fixes it, other times I have to delete the contents of the node_modules folder completely.  Can't see anything wrong in the npm log files and I don't know if there are any other logs where I can see verbose output from the task?

**Comment by HuihuiWu-Microsoft** [comment] 2022-07-20 08:51
> Checking and installing NPM package

Hi @ichivers , that should be a different issue which is due to prerequisite checker. And from the log you pasted here, it comes from react-based Azure tab app. @qinezh could you help check?

**Comment by kuojianlu** [comment] 2022-07-20 09:44
@ichivers Sorry for the inconvenience. This is a bug caused by concurrent progress bar. The workaround is to retry. This bug has been already fixed in #5471. The fix will take effect in next release (next week). Please use the latest release then.

FYI: @HuihuiWu-Microsoft @qinezh

**Closed** 2022-07-28 05:35 UTC
Labels: investigating, needs more info, TA:E2E, no recent activity
