### ISSUE TITLE
bug report: teamsAppExtendToM365.UnhandledError

### ISSUE THREAD

**Issue by vayinapurapu** [OfficeDev/TeamsFx#8986] opened 2023-06-11 06:26 UTC
An unexpected error has occurred while performing the <REDACTED: user-file-path> task. The reason for this error is: Unexpected token '�', "���xo��3f"... is not valid JSON. Welcome to report this issue by clicking on the provided "Issue Link", so that we can investigate and resolve the problem as soon as possible.

stack:
SyntaxError: Unexpected token '�', "���xo��3f"... is not valid JSON
    at JSON.parse (<anonymous>)
    at ConvertTokenToJson (<REDACTED: user-file-path>:8:5763866)
    at CodeFlowLogin.<anonymous> (<REDACTED: user-file-path>:8:5756089)
    at Generator.next (<anonymous>)
    at fulfilled (<REDACTED: user-file-path>:8:5750045)

**Comment by vayinapurapu** [comment] 2023-06-11 06:26
when trying to create a react app using teams tool kit i am getting above error

**Comment by kuojianlu** [comment] 2023-06-13 02:04
Duplicate of https://github.com/OfficeDev/TeamsFx/issues/8741

**Closed by kuojianlu** 2023-06-13 02:04 UTC
Labels: investigating, TA:Infra, needs attention
