### ISSUE TITLE
Bot skipping some messages

### ISSUE THREAD

**Issue by whiteGhost-08** [OfficeDev/TeamsFx#9131] opened 2023-06-26 11:24 UTC
**Describe the bug**
Suddenly my bot started skipping messages 

More info: 
I have been trying to develop a notification bot. I made some progress, but since this morning, my bot started to skip of my messages. I thought I had made a mistake in the code somewhere, so I decided to create a new one. I used the Teams Toolkit extension (version: 5.0.1) to create a new notification message Restify bot using ts and started its debugging session. However, I'm still encountering the same issue in the new bot as well.

I am using a Microsoft 365 developer account with sideloading enabled, and this code is running locally on localhost.

**Screenshots**
<img width="756" alt="Screenshot 2023-06-26 at 4 45 06 PM" src="https://github.com/OfficeDev/TeamsFx/assets/83160894/85eee254-54b2-44b6-a233-28c3fa3dc9ed">

onMessage handler code : 
<img width="817" alt="Screenshot 2023-06-26 at 4 53 18 PM" src="https://github.com/OfficeDev/TeamsFx/assets/83160894/48f5749f-9879-4f4d-8bc7-e7e3f8e0d55f">

**Comment by Engage-r** [comment] 2023-06-26 14:41
+1 I'm facing this issue too  $_$

**Comment by ravindran-a** [comment] 2023-06-26 18:41
+1 facing same issues.

**Comment by lukaszlukjanowicz-alation** [comment] 2023-06-27 05:57
+1

**Comment by HuihuiWu-Microsoft** [comment] 2023-06-27 09:03
Should be the same root cause with https://github.com/OfficeDev/TeamsFx/issues/9132

**Comment by SebastianNowacki** [comment] 2023-06-28 06:31
+1

**Comment by arjunumenon** [comment] 2023-06-28 15:00
Thanks a lot for confirming that the issue is there across the tenant. Appreciate in taking it up to the engineering team.
Can we get an ETA on that front please.

**Comment by HuihuiWu-Microsoft** [comment] 2023-06-29 02:39
@arjunumenon There's a Sev2 ticket tracking this issue now, we haven't got an ETA yet, will update once there is.

**Comment by swatDong** [comment] 2023-07-03 03:28
The upstream service issue has been resolved. Closing this.

**Closed by swatDong** 2023-07-03 03:28 UTC
Labels: *duplicate, needs attention
