### ISSUE TITLE
Upload failed due to an invalid BotId in your manifest.

### ISSUE THREAD

**Issue by christophemacabiau** [OfficeDev/TeamsFx#8261] opened 2023-04-03 10:13 UTC
**Describe the bug**
Impossible to launch the app

**To Reproduce**
The application is a tab/bot app created with teams toolkit.
The manifest is correctly validated by developer portal.

**Screenshots**
![image](https://user-images.githubusercontent.com/621068/229480817-0ab3e156-24fb-4d6a-922a-9673c1acb869.png)

**VS Code Extension Information (please complete the following information):**
 - OS: linux
 - Version 4.2.4

**Comment by christophemacabiau** [comment] 2023-04-03 10:36
maybe related to #7608

**Comment by nliu-ms** [comment] 2023-04-04 06:22
Hey @christophemacabiau , from the screenshot you cannot launch the Teams app for dev env right? Does your local debug Teams app work?

#7608 is concerning launch Teams app for local debug / F5 experience. So it might be different.

**Comment by christophemacabiau** [comment] 2023-04-04 09:44
Yes, the local debug teams work.

**Comment by msmarkglad** [comment] 2023-04-05 02:44
I am getting the same error, just published now and that worked, but I can't open the bot in Teams.

**Comment by nliu-ms** [comment] 2023-04-06 02:28
Thanks @christophemacabiau , @msmarkglad . Can you please provide following information:

1) Did you successfully launch this app before and it failed suddenly? Or you can never do it.
2) Can you please check if the Teams channel is correctly configured in Azure bot? Cause this error message usually comes from missing/wrong Teams channel configuration.
![image](https://user-images.githubusercontent.com/71362691/230254366-f1a95e80-7554-4351-9afc-6dc956c5cbf8.png)

3) Can you launch other Teams bot app?

**Comment by christophemacabiau** [comment] 2023-04-06 15:35
Hi @nliu-ms,

Thank you for your answer.

1. It worked at the beggining,
2. I don't know why but everytime I click on Channels/Microsoft teams, I have to agree the terms of service. Could it be the problem?
![image](https://user-images.githubusercontent.com/621068/230427647-28f285ec-078d-4aba-ae21-ddfd36cccb03.png)
When I click on "Open in teams", it seems to work
3. How can I provide you the steps to reproduce? Do you need an access to the app?

**Comment by msmarkglad** [comment] 2023-04-06 18:33
I have never been able to launch it. I got the error the first time I tried. Here's the steps:

[cid:dda4a0fc-7d7d-40c3-9eed-22630a86fa47]

[cid:a5ae3999-d51c-4086-a21d-70dd2256f2de]

[cid:918b07d9-e4a8-4d29-90de-bfe888f8c998]

I'm doing all this in the PVA app in teams, so I'm not actually going into Azure bot. I'm pretty new at this, so if I need to go into Azure bot to look, if you can point me to how, I can see what's there.

Thanks!
Mark
________________________________

**Comment by nliu-ms** [comment] 2023-04-07 02:10
Thanks @msmarkglad , sorry I cannot see the screenshots in your comments. Can you please post the steps again?
[cid:dda4a0fc-7d7d-40c3-9eed-22630a86fa47]

[cid:a5ae3999-d51c-4086-a21d-70dd2256f2de]

[cid:918b07d9-e4a8-4d29-90de-bfe888f8c998]

As you're using PVA app to create the bot, then how do you use Teams Toolkit with it? Did you put that bot id into a project generated by Teams Toolkit? Thanks!

**Comment by nliu-ms** [comment] 2023-04-07 02:24
Thanks @christophemacabiau , from the screenshots there are 3 issues in "Microsoft Teams" channel, it might be the root cause. Can you find out the exact issues and fix them to make the Teams channel healthy? Then try to launch the Teams app again to see if it works. "agree the terms of service" is no the problem.

For the workaround I'm thinking if you can create a new Azure bot. Below are the steps:
1) Create another environment
![image](https://user-images.githubusercontent.com/71362691/230527912-b454a774-5f35-493d-9ed7-6aeb065c44bb.png)
2) Provision that environment
3) Launch the new Teams app.

**Comment by christophemacabiau** [comment] 2023-04-07 14:23
Hi @nliu-ms,

Thank you for your workaround, it worked starting from a fresh environment!

However now I have another problem: when I try to send it a notification, the bot has no installations, no members... Can you give some hint?

**Comment by nliu-ms** [comment] 2023-04-10 01:44
@christophemacabiau Great to hear it works!

Hey @IvanJobs , do you know the possible reasons for Christopher's issue:

> Hi @nliu-ms,
> 
> Thank you for your workaround, it worked starting from a fresh environment!
> 
> However now I have another problem: when I try to send it a notification, the bot has no installations, no members... Can you give me some hint?

**Comment by yukun-dong** [comment] 2023-04-19 06:18
> Hi @nliu-ms,
> 
> Thank you for your workaround, it worked starting from a fresh environment!
> 
> However now I have another problem: when I try to send it a notification, the bot has no installations, no members... Can you give me some hint?

Hi @christophemacabiau, could you please provide which template you are using? Is it a notification bot?
That may help identify the issue, thanks.

**Comment by christophemacabiau** [comment] 2023-04-19 08:32
Hi @yukun-dong,
Thank you for your answer.
I started with a tab application created by teams toolkit, and I further added the bot feature. It was never possible to make it work.

**Comment by yukun-dong** [comment] 2023-04-21 03:12
Hi @christophemacabiau,

Sorry I didn't make my question clear, so let me clarify.

Did you select this "Notification bot"(below picture) when adding the bot feature into your tab project? I see you are using bot's installations and bot members so it should be a notification bot, but I just want to double confirm. Thanks.
![image](https://user-images.githubusercontent.com/25220706/233531503-eb86fd1f-e2d9-463b-9b7b-fd3bec89bc3e.png)

**Comment by christophemacabiau** [comment] 2023-04-21 10:05
Hi @yukun-dong 
yes you are right: a notification bot

**Comment by swatDong** [comment] 2023-04-23 08:38
@christophemacabiau you mentioned that you created a tab first, then added the notification bot, right?
If so, it's probably due to the same cause as [this issue](https://github.com/OfficeDev/TeamsFx-Samples/issues/615#issuecomment-1516086074).

In general, it may be caused by **authentication is enabled on Azure App Service or Azure Function**, and the workaround is to disable **Authentication settings**. As described in [here](https://github.com/OfficeDev/TeamsFx-Samples/issues/615#issuecomment-1517151589) as well.

**Comment by swatDong** [comment] 2023-04-25 01:41
Pinned the workaround for quick reference (https://github.com/OfficeDev/TeamsFx/issues/8527).

**Comment by hemxnt-saini** [comment] 2023-06-27 08:36
Hi guys, I'm still facing this issue, I have created a simple bot, provision and deploy it with teamsfx commands, it passes all the validations checks and when I try to upload the appPackage on teams, it throws me this error: 'Upload failed due to an invalid BotId in your manifest' continuously. 

@christophemacabiau

**Comment by VKZycus** [comment] 2023-06-27 09:00
Hi Team, I am also facing issue from last two days.While running the bot locally we are getting
![image](https://github.com/OfficeDev/TeamsFx/assets/104554101/39fdc5d6-0afe-4923-a59b-120e7dfbe321)

"Upload failed due to an invalid BotId in your manifest."
Botid is present on developer portal also password is correct.

**Comment by adashen** [comment] 2023-07-03 07:06
Please refer to the pinned the workaround for quick reference (https://github.com/OfficeDev/TeamsFx/issues/8527).

**Comment by pmcilreavy** [comment] 2024-03-21 04:35
This is happening again randomly today to an app the was already working and now it gives "Upload failed due to an invalid BotId in your manifest".

To isolate my app for the problem I created a brand new Teams Echo Bot using the Visual Studio template and follow the instructions and also get "Upload failed due to an invalid BotId in your manifest".

Really need this resolved ASAP.

**Comment by sarhaan7** [comment] 2024-03-21 05:07
Yep same, i have a simple chatbot running, had to reset it today and it no longer works.
- The new teams client just fails with `Uncaught (in promise) SyntaxError: "[object Object]" is not valid JSON` and the old teams client returns `Upload failed due to an invalid BotId in your manifest.`
- The manifest is correctly validated by developer portal.
- it was working just fine as of 3pm EST on March 20th.

Appreciate any help and thanks in advance for fixing this!

**Comment by nliu-ms** [comment] 2024-03-25 07:09
This issue has been mitigated and tracked by https://github.com/OfficeDev/TeamsFx/issues/11146, close this one.

**Closed by nliu-ms** 2024-03-25 07:09 UTC
Labels: investigating, TA:E2E, needs attention
