### ISSUE TITLE
bug report: arm/deploy.UnhandledError

### ISSUE THREAD

**Issue by theodury** [OfficeDev/TeamsFx#10902] opened 2024-02-22 15:16 UTC
Cannot redefine property: stack

stack:
UnhandledError: Cannot redefine property: stack
    at getError (<REDACTED: user-file-path>:14:6313245)
    at Object.wrapRun (<REDACTED: user-file-path>:14:6313423)
    at processTicksAndRejections (node:<REDACTED: user-file-path>:95:5)
    at ArmDeployDriver.execute (<REDACTED: user-file-path>:14:6056370)
    at Lifecycle.executeImpl (<REDACTED: user-file-path>:14:5935227)
    at Lifecycle.execute (<REDACTED: user-file-path>:14:5932384)
    at Coordinator.provision (<REDACTED: user-file-path>:14:5976180)
    at Coordinator.<anonymous> (<REDACTED: user-file-path>:14:6600016)
    at FxCore.provisionResources (<REDACTED: user-file-path>:14:6529125)
    at FxCore.exports.EnvWriterMW (<REDACTED: user-file-path>:14:6441982)
    at FxCore.exports.ContextInjectorMW (<REDACTED: user-file-path>:14:6603768)
    at FxCore.exports.ConcurrentLockerMW (<REDACTED: user-file-path>:14:6602719)
    at envLoaderMWImpl (<REDACTED: user-file-path>:14:6441929)
    at FxCore.<anonymous> (<REDACTED: user-file-path>:14:6440843)
    at FxCore.exports.ProjectMigratorMWV3 (<REDACTED: user-file-path>:14:6634319)
    at FxCore.exports.ErrorHandlerMW (<REDACTED: user-file-path>:14:6604265)
    at FxCore.<anonymous> (<REDACTED: user-file-path>:14:6600016)

**Comment by andremarques023** [comment] 2024-02-23 20:50
We are facing the same issue.

**Comment by italogoncalvessilveira** [comment] 2024-02-24 00:31
Same error here

**Comment by chandanpjain** [comment] 2024-02-27 01:20
Facing same error when trying the sample python conversation bot.

**Comment by jayzhang** [comment] 2024-02-27 06:31
@theodury Thanks for feedback. We will fix it.

**Comment by theodury** [comment] 2024-02-27 15:01
@jayzhang  Ok if you need anymore detail i will be welcome to have a call with you if necessary: 

I was thinking that was an authorization issue : 

![image](https://github.com/OfficeDev/TeamsFx/assets/6726393/d7f2fdfe-63de-4676-a461-172a1b0b06ec)

![image](https://github.com/OfficeDev/TeamsFx/assets/6726393/064674cf-ea70-4400-872b-a4ca852089ea)

**Comment by theodury** [comment] 2024-02-28 15:51
@jayzhang By the way i did comment this line because of this issue : 

![image](https://github.com/OfficeDev/TeamsFx/assets/6726393/9bd57591-c01a-48ae-a2b8-9c9eb627af2d)

![image](https://github.com/OfficeDev/TeamsFx/assets/6726393/44cfbc7d-6cb1-489f-8e2a-e1e7d6ff3b85)


```

# yaml-language-server: $schema=https://aka.ms/teams-toolkit/1.0.0/yaml.schema.json
# Visit https://aka.ms/teamsfx-v5.0-guide for details on this file
# Visit https://aka.ms/teamsfx-actions for details on actions
version: 1.0.0

environmentFolderPath: ./env

# Triggered when 'teamsfx provision' is executed
provision:
  - uses: teamsApp/create # Creates a Teams app
    with:
      name: TeamsChef-${{TEAMSFX_ENV}} # Teams app name
    writeToEnvironmentFile:
      # Write the information of installed dependencies into environment file for the specified environment variable(s).
      teamsAppId: TEAMS_APP_ID

  - uses: botAadApp/create # Creates a new AAD app for Bot Registration.
    with:
      name: TeamsChef
    writeToEnvironmentFile:
      botId: BOT_ID
      botPassword: SECRET_BOT_PASSWORD

  - uses: arm/deploy # Deploy given ARM templates parallelly.
    with:
      subscriptionId: ${{AZURE_SUBSCRIPTION_ID}} # The AZURE_SUBSCRIPTION_ID is a built-in environment variable. TeamsFx will ask you select one subscription if its value is empty. You're free to reference other environment varialbe here, but TeamsFx will not ask you to select subscription if it's empty in this case.
      resourceGroupName: ${{AZURE_RESOURCE_GROUP_NAME}} # The AZURE_RESOURCE_GROUP_NAME is a built-in environment variable. TeamsFx will ask you to select or create one resource group if its value is empty. You're free to reference other environment varialbe here, but TeamsFx will not ask you to select or create resource grouop if it's empty in this case.
      templates:
        - path: ./infra/azure.bicep
          parameters: ./infra/azure.parameters.json
          deploymentName: Create-resources-for-bot
      bicepCliVersion: v0.9.1 # Teams Toolkit will download this bicep CLI version from github for you, will use bicep CLI in PATH if you remove this config.
    # Output: every bicep output will be persisted in current environment's .env file with certain naming conversion. Refer https://aka.ms/teamsfx-actions/arm-deploy for more details on the naming conversion rule.

  - uses: teamsApp/validateManifest # Validate using manifest schema
    with:
      manifestPath: ./teamsAppManifest/manifest.json # Path to manifest template
  - uses: teamsApp/zipAppPackage # Build Teams app package with latest env value
    with:
      manifestPath: ./teamsAppManifest/manifest.json # Path to manifest template
      outputZipPath: ./build/teamsAppManifest/appPackage.${{TEAMSFX_ENV}}.zip
      outputJsonPath: ./build/teamsAppManifest/manifest.${{TEAMSFX_ENV}}.json
  - uses: teamsApp/update # Apply the Teams app manifest to an existing Teams app in Teams Developer Portal. Will use the app id in manifest file to determine which Teams app to update.
    with:
      appPackagePath: ./build/teamsAppManifest/appPackage.${{TEAMSFX_ENV}}.zip # Relative path to this file. This is the path for built zip file.
    # writeToEnvironmentFile:
    #   # Write the information of installed dependencies into environment file for the specified environment variable(s).
    #   teamsAppId: TEAMS_APP_ID

# Triggered when 'teamsfx deploy' is executed
# deploy:
#   - uses: azureAppService/deploy # Deploy bits to Azure App Serivce
#     with:
#       distributionPath: . # Deploy base folder
#       ignoreFile: ./.appserviceignore # Can be changed to any ignore file location, leave blank will ignore nothing
#       resourceId: ${{BOT_AZURE_APP_SERVICE_RESOURCE_ID}} # The resource id of the cloud resource to be deployed to. This key will be generated by arm/deploy action automatically. You can replace it with your existing Azure Resource id or add it to your environment variable file.

# Triggered when 'teamsfx publish' is executed
publish:
  - uses: teamsApp/validateManifest # Validate using manifest schema
    with:
      manifestPath: ./teamsAppManifest/manifest.json # Path to manifest template
  - uses: teamsApp/zipAppPackage
    with:
      manifestPath: ./teamsAppManifest/manifest.json # Path to manifest template
      outputZipPath: ./build/teamsAppManifest/appPackage.${{TEAMSFX_ENV}}.zip
      outputJsonPath: ./build/teamsAppManifest/manifest.${{TEAMSFX_ENV}}.json
  - uses: teamsApp/update # Apply the Teams app manifest to an existing Teams app in Teams Developer Portal. Will use the app id in manifest file to determine which Teams app to update.
    with:
      appPackagePath: ./build/teamsAppManifest/appPackage.${{TEAMSFX_ENV}}.zip # Relative path to this file. This is the path for built zip file.
    # writeToEnvironmentFile:
    #   # Write the information of installed dependencies into environment file for the specified environment variable(s).
    #   teamsAppId: TEAMS_APP_ID
  - uses: teamsApp/publishAppPackage # Publish the app to Teams Admin Center (https://admin.teams.microsoft.com/policies/manage-apps) for review and approval
    with:
      appPackagePath: ./build/teamsAppManifest/appPackage.${{TEAMSFX_ENV}}.zip
    writeToEnvironmentFile:
      # Write the information of installed dependencies into environment file for the specified environment variable(s).
      publishedAppId: TEAMS_APP_PUBLISHED_APP_ID
projectId: dc566bd8-248c-4295-8b72-9220810ffb6c
```

**Comment by andremarques023** [comment] 2024-03-05 11:42
@jayzhang any updates on the root cause of this issue?

**Comment by jayzhang** [comment] 2024-03-06 07:01
@

> @jayzhang By the way i did comment this line because of this issue :
> 
> ![image](https://private-user-images.githubusercontent.com/6726393/308620208-9bd57591-c01a-48ae-a2b8-9c9eb627af2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MDgxMjYsIm5iZiI6MTcwOTcwNzgyNiwicGF0aCI6Ii82NzI2MzkzLzMwODYyMDIwOC05YmQ1NzU5MS1jMDFhLTQ4YWUtYTJiOC05YzllYjYyN2FmMmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDZUMDY1MDI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzQ1ZGU3YTNmNjMxYzIyYmI2OGMyOTU1ZGY5NGRjM2QxZDBjMzVjYjViZWQyMDk0ZmI1MmFjODRjODhjMzlkMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.G4xAUObBrZAxK4as3sB8OHASV6ZOci61CSHZqe-4DOw)
> 
> ![image](https://private-user-images.githubusercontent.com/6726393/308620710-44cfbc7d-6cb1-489f-8e2a-e1e7d6ff3b85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MDgxMjYsIm5iZiI6MTcwOTcwNzgyNiwicGF0aCI6Ii82NzI2MzkzLzMwODYyMDcxMC00NGNmYmM3ZC02Y2IxLTQ4OWYtOGUyYS1lMWU3ZDZmZjNiODUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDZUMDY1MDI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjE2OTA0ZmFkNDkyMjIyOTNkNzdmMzkzOTgyYjRlMzEzNGY1Y2Q5ZGNhMmFiODliZjhhM2I5YzZhN2ZiNmZkNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8NqFSwppcWUV2PCeoLoC-3p7HV0Xab2HO8lzC99wZIc)
> 
> ```
> 
> # yaml-language-server: $schema=https://aka.ms/teams-toolkit/1.0.0/yaml.schema.json
> # Visit https://aka.ms/teamsfx-v5.0-guide for details on this file
> # Visit https://aka.ms/teamsfx-actions for details on actions
> version: 1.0.0
> 
> environmentFolderPath: ./env
> 
> # Triggered when 'teamsfx provision' is executed
> provision:
>   - uses: teamsApp/create # Creates a Teams app
>     with:
>       name: TeamsChef-${{TEAMSFX_ENV}} # Teams app name
>     writeToEnvironmentFile:
>       # Write the information of installed dependencies into environment file for the specified environment variable(s).
>       teamsAppId: TEAMS_APP_ID
> 
>   - uses: botAadApp/create # Creates a new AAD app for Bot Registration.
>     with:
>       name: TeamsChef
>     writeToEnvironmentFile:
>       botId: BOT_ID
>       botPassword: SECRET_BOT_PASSWORD
> 
>   - uses: arm/deploy # Deploy given ARM templates parallelly.
>     with:
>       subscriptionId: ${{AZURE_SUBSCRIPTION_ID}} # The AZURE_SUBSCRIPTION_ID is a built-in environment variable. TeamsFx will ask you select one subscription if its value is empty. You're free to reference other environment varialbe here, but TeamsFx will not ask you to select subscription if it's empty in this case.
>       resourceGroupName: ${{AZURE_RESOURCE_GROUP_NAME}} # The AZURE_RESOURCE_GROUP_NAME is a built-in environment variable. TeamsFx will ask you to select or create one resource group if its value is empty. You're free to reference other environment varialbe here, but TeamsFx will not ask you to select or create resource grouop if it's empty in this case.
>       templates:
>         - path: ./infra/azure.bicep
>           parameters: ./infra/azure.parameters.json
>           deploymentName: Create-resources-for-bot
>       bicepCliVersion: v0.9.1 # Teams Toolkit will download this bicep CLI version from github for you, will use bicep CLI in PATH if you remove this config.
>     # Output: every bicep output will be persisted in current environment's .env file with certain naming conversion. Refer https://aka.ms/teamsfx-actions/arm-deploy for more details on the naming conversion rule.
> 
>   - uses: teamsApp/validateManifest # Validate using manifest schema
>     with:
>       manifestPath: ./teamsAppManifest/manifest.json # Path to manifest template
>   - uses: teamsApp/zipAppPackage # Build Teams app package with latest env value
>     with:
>       manifestPath: ./teamsAppManifest/manifest.json # Path to manifest template
>       outputZipPath: ./build/teamsAppManifest/appPackage.${{TEAMSFX_ENV}}.zip
>       outputJsonPath: ./build/teamsAppManifest/manifest.${{TEAMSFX_ENV}}.json
>   - uses: teamsApp/update # Apply the Teams app manifest to an existing Teams app in Teams Developer Portal. Will use the app id in manifest file to determine which Teams app to update.
>     with:
>       appPackagePath: ./build/teamsAppManifest/appPackage.${{TEAMSFX_ENV}}.zip # Relative path to this file. This is the path for built zip file.
>     # writeToEnvironmentFile:
>     #   # Write the information of installed dependencies into environment file for the specified environment variable(s).
>     #   teamsAppId: TEAMS_APP_ID
> 
> # Triggered when 'teamsfx deploy' is executed
> # deploy:
> #   - uses: azureAppService/deploy # Deploy bits to Azure App Serivce
> #     with:
> #       distributionPath: . # Deploy base folder
> #       ignoreFile: ./.appserviceignore # Can be changed to any ignore file location, leave blank will ignore nothing
> #       resourceId: ${{BOT_AZURE_APP_SERVICE_RESOURCE_ID}} # The resource id of the cloud resource to be deployed to. This key will be generated by arm/deploy action automatically. You can replace it with your existing Azure Resource id or add it to your environment variable file.
> 
> # Triggered when 'teamsfx publish' is executed
> publish:
>   - uses: teamsApp/validateManifest # Validate using manifest schema
>     with:
>       manifestPath: ./teamsAppManifest/manifest.json # Path to manifest template
>   - uses: teamsApp/zipAppPackage
>     with:
>       manifestPath: ./teamsAppManifest/manifest.json # Path to manifest template
>       outputZipPath: ./build/teamsAppManifest/appPackage.${{TEAMSFX_ENV}}.zip
>       outputJsonPath: ./build/teamsAppManifest/manifest.${{TEAMSFX_ENV}}.json
>   - uses: teamsApp/update # Apply the Teams app manifest to an existing Teams app in Teams Developer Portal. Will use the app id in manifest file to determine which Teams app to update.
>     with:
>       appPackagePath: ./build/teamsAppManifest/appPackage.${{TEAMSFX_ENV}}.zip # Relative path to this file. This is the path for built zip file.
>     # writeToEnvironmentFile:
>     #   # Write the information of installed dependencies into environment file for the specified environment variable(s).
>     #   teamsAppId: TEAMS_APP_ID
>   - uses: teamsApp/publishAppPackage # Publish the app to Teams Admin Center (https://admin.teams.microsoft.com/policies/manage-apps) for review and approval
>     with:
>       appPackagePath: ./build/teamsAppManifest/appPackage.${{TEAMSFX_ENV}}.zip
>     writeToEnvironmentFile:
>       # Write the information of installed dependencies into environment file for the specified environment variable(s).
>       publishedAppId: TEAMS_APP_PUBLISHED_APP_ID
> projectId: dc566bd8-248c-4295-8b72-9220810ffb6c
> ```

@theodury  The yml schema version is too old to support `writeToEnvironmentFile` property. You can try to use the latest v1.3 instead of 1.0.0 and try again. I think not every  action supports `writeToEnvironmentFile` property. You can troubleshoot by your self when you change the schema version.

**Comment by jayzhang** [comment] 2024-03-06 07:04
> @jayzhang Okay, if you need any more details, I would be happy to have a call with you if necessary.
> 
> I thought it was an authorization issue:
> 
> ![image](https://private-user-images.githubusercontent.com/6726393/308220509-d7f2fdfe-63de-4676-a461-172a1b0b06ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MDgxMjYsIm5iZiI6MTcwOTcwNzgyNiwicGF0aCI6Ii82NzI2MzkzLzMwODIyMDUwOS1kN2YyZmRmZS02M2RlLTQ2NzYtYTQ2MS0xNzJhMWIwYjA2ZWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDZUMDY1MDI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGEyNTVjMDk0ZjI4NmEwMmQ1ZGU0MjNiNzZhNDc2ZWMxYjA0YzcwZmEwMGMxMTZjOWRmY2RmN2M0ZDgyYTg4YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9stnpV_bxx9RqHZ8x6PO2mCUskHbULdzS0LkN-ny2t8)
> 
> ![image](https://private-user-images.githubusercontent.com/6726393/308220097-064674cf-ea70-4400-872b-a4ca852089ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MDgxMjYsIm5iZiI6MTcwOTcwNzgyNiwicGF0aCI6Ii82NzI2MzkzLzMwODIyMDA5Ny0wNjQ2NzRjZi1lYTcwLTQ0MDAtODcyYi1hNGNhODUyMDg5ZWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDZUMDY1MDI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTU1NWQ2ZTdiNTZiNjA3MzQ2YzI2YWMxNTk0MWYzMjQ2N2MyYmIxOGU2NjIwYWFhOWFiMGE2Zjg3NDA1M2Y3ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zi6eK3EDPBq_GG04kXTXbAa9j9T2IpiEsbr0PinkvQQ)

Yes, the reason why TTK not expose this error is because there is a bug when the error is being constructed, which is fixed in the next prerelease version.

**Comment by maxsporer** [comment] 2024-03-06 16:42
When will the next prerelease version be available?

**Comment by evelyn-cristina** [comment] 2024-03-07 18:25
I'm experiencing the same problem. When will be have a fix to apply it, please?

**Comment by evelyn-cristina** [comment] 2024-03-11 17:18
> The issue is milestoned with sprint milestone CY24Q1-2Wk12 (Feb 25 - Mar 09) and a work item created: https://msazure.visualstudio.com/9660fff2-2363-48b0-9e15-64df2283e932/_workitems/edit/27087028

Is this ready for download?

**Comment by xzf0587** [comment] 2024-03-12 02:27
@evelyn-cristina, as the pre-release version has fixed this bug. You can  upgrade to the pre-release version in vscode extension.
![image](https://github.com/OfficeDev/TeamsFx/assets/16380704/ee4d7338-2347-4436-b0ce-5c3c2828bf22)
And try it again.

**Closed as completed** 2024-03-14 08:10 UTC
Labels: investigating, TA:E2E
