### ISSUE TITLE
bug report: unknown.TypeError

### ISSUE THREAD

**Issue by sivateja1995** [OfficeDev/TeamsFx#3575] opened 2022-01-07 09:48 UTC
Cannot read property 'message' of undefined

stack:
TypeError: Cannot read property 'message' of undefined
    at SqlPlugin.runWithSqlError (<REDACTED: user-file-path>:2:6230120)
    at Object.configureResourceAdapter (<REDACTED: user-file-path>:2:6279021)
    at SqlPluginV2.configureResource (<REDACTED: user-file-path>:2:6271685)
    at async Promise.all (index 1)
    at Object.executeConcurrently (<REDACTED: user-file-path>:2:6480726)
    at TeamsAppSolutionV2.provisionResource [as provisionResources] (<REDACTED: user-file-path>:2:6524684)
    at FxCore.provisionResources (<REDACTED: user-file-path>:2:5049192)
    at FxCore.<anonymous> (<REDACTED: user-file-path>:2:5095727)
    at FxCore.exports.ProjectSettingsWriterMW (<REDACTED: user-file-path>:2:5149788)
    at FxCore.exports.ContextInjectorMW (<REDACTED: user-file-path>:2:5086207)
    at FxCore.exports.QuestionModelMW (<REDACTED: user-file-path>:2:5161288)
    at FxCore.<anonymous> (<REDACTED: user-file-path>:2:5162187)
    at FxCore.<anonymous> (<REDACTED: user-file-path>:2:5092957)
    at FxCore.exports.ProjectSettingsLoaderMW (<REDACTED: user-file-path>:2:5148580)
    at FxCore.exports.ProjectMigratorMW (<REDACTED: user-file-path>:2:5145588)
    at FxCore.<anonymous> (<REDACTED: user-file-path>:2:5162925)
    at FxCore.exports.ConcurrentLockerMW (<REDACTED: user-file-path>:2:5085475)
    at FxCore.exports.ErrorHandlerMW (<REDACTED: user-file-path>:2:5098119)

**Comment by sivateja1995** [comment] 2022-01-07 09:51
````
here is the complete details of the error
````
[Error] - getaddrinfo ENOTFOUND api.ipify.org
[2022-01-07T09:47:44.224Z] [Info] - [Function] Start to run command: node -v
[2022-01-07T09:47:44.258Z] [Error] - code:unknown.TypeError, message: Cannot read property 'message' of undefined, stack: TypeError: Cannot read property 'message' of undefined
    at SqlPlugin.runWithSqlError (/home/inncrewin/.vscode-server/extensions/teamsdevapp.ms-teams-vscode-extension-3.1.1/out/src/extension.js:2:6230120)
    at Object.configureResourceAdapter (/home/inncrewin/.vscode-server/extensions/teamsdevapp.ms-teams-vscode-extension-3.1.1/out/src/extension.js:2:6279021)
    at SqlPluginV2.configureResource (/home/inncrewin/.vscode-server/extensions/teamsdevapp.ms-teams-vscode-extension-3.1.1/out/src/extension.js:2:6271685)
    at async Promise.all (index 1)
    at Object.executeConcurrently (/home/inncrewin/.vscode-server/extensions/teamsdevapp.ms-teams-vscode-extension-3.1.1/out/src/extension.js:2:6480726)
    at TeamsAppSolutionV2.provisionResource [as provisionResources] (/home/inncrewin/.vscode-server/extensions/teamsdevapp.ms-teams-vscode-extension-3.1.1/out/src/extension.js:2:6524684)
    at FxCore.provisionResources (/home/inncrewin/.vscode-server/extensions/teamsdevapp.ms-teams-vscode-extension-3.1.1/out/src/extension.js:2:5049192)
    at FxCore.<anonymous> (/home/inncrewin/.vscode-server/extensions/teamsdevapp.ms-teams-vscode-extension-3.1.1/out/src/extension.js:2:5095727)
    at FxCore.exports.ProjectSettingsWriterMW (/home/inncrewin/.vscode-server/extensions/teamsdevapp.ms-teams-vscode-extension-3.1.1/out/src/extension.js:2:5149788)
    at FxCore.exports.ContextInjectorMW (/home/inncrewin/.vscode-server/extensions/teamsdevapp.ms-teams-vscode-extension-3.1.1/out/src/extension.js:2:5086207)
    at FxCore.exports.QuestionModelMW (/home/inncrewin/.vscode-server/extensions/teamsdevapp.ms-teams-vscode-extension-3.1.1/out/src/extension.js:2:5161288)
    at FxCore.<anonymous> (/home/inncrewin/.vscode-server/extensions/teamsdevapp.ms-teams-vscode-extension-3.1.1/out/src/extension.js:2:5162187)
    at FxCore.<anonymous> (/home/inncrewin/.vscode-server/extensions/teamsdevapp.ms-teams-vscode-extension-3.1.1/out/src/extension.js:2:5092957)
    at FxCore.exports.ProjectSettingsLoaderMW (/home/inncrewin/.vscode-server/extensions/teamsdevapp.ms-teams-vscode-extension-3.1.1/out/src/extension.js:2:5148580)
    at FxCore.exports.ProjectMigratorMW (/home/inncrewin/.vscode-server/extensions/teamsdevapp.ms-teams-vscode-extension-3.1.1/out/src/extension.js:2:5145588)
    at FxCore.<anonymous> (/home/inncrewin/.vscode-server/extensions/teamsdevapp.ms-teams-vscode-extension-3.1.1/out/src/extension.js:2:5162925)
    at FxCore.exports.ConcurrentLockerMW (/home/inncrewin/.vscode-server/extensions/teamsdevapp.ms-teams-vscode-extension-3.1.1/out/src/extension.js:2:5085475)
    at FxCore.exports.ErrorHandlerMW (/home/inncrewin/.vscode-server/extensions/teamsdevapp.ms-teams-vscode-extension-3.1.1/out/src/extension.js:2:5098119)

**Comment by xzf0587** [comment] 2022-01-13 18:16
@sivateja1995, sorry for the late reply.
Thanks for reporting this bug. 
It is caused by an error of DNS since the code tried to get client external IP address from api.ipify.org and DNS failed to resolve this domain. But The error handling trigged a potential bug and output confused error message. We will fix it as soon as possible.  

Feel free to ping me again!

**Comment by sivateja1995** [comment] 2022-01-17 11:26
Hi, when can I expect the issue to be resolved? as I working on a project which is needed to be deployed to be soon.

**Comment by xzf0587** [comment] 2022-01-18 03:29
Hi @sivateja1995,
Sorry for late reply.
We will fix it in the PR https://github.com/OfficeDev/TeamsFx/pull/3693.
And the expected release date is 02/07.
Actually this bug happens when the tool tries to access to "https://api.ipify.org" fails. According to the detailed error pasted, there was a DNS/network to access to "https://api.ipify.org".
As a walk-around for the bug, if the access to "https://api.ipify.org" is ok, the bug will not be trigged.
I Hope it helps.

**Comment by xzf0587** [comment] 2022-02-14 01:49
Hi @sivateja1995,
The new version of teamsfx toolkit [https://github.com/OfficeDev/TeamsFx/releases/tag/ms-teams-vscode-extension%403.3.0](url) has released. The bug you reported should be fixed. Please try again. 
Thanks for your report.

**Comment by adashen** [comment] 2022-02-14 02:49
close as fixed

**Closed by adashen** 2022-02-14 02:49 UTC
Labels: bug, TA:Auth
