### ISSUE TITLE
Outlook Desktop blocking authentication url from opening

### ISSUE THREAD

**Issue by akanjimm** [OfficeDev/TeamsFx#7069] opened 2022-12-02 07:34 UTC
### Describe the bug
Authentication popup is being blocked in Outlook Desktop, thus preventing the user from logging-in or consenting to permissions. The user also gets redirected to the browser which displays a blank screen.

#### Error in Outlook desktop console
ErrorWithCode.ConsentFailed: Consent failed for the scope User.Read User.ReadBasic.All with error: browser is blocking the url to open

#### Error in browser
No Parent window found

### To Reproduce
Create a new Teams app using the Teams Toolkit and selecting SSO enabled personal tab (Extended Teams apps across Microsoft 365). Run and open the app on Outlook Desktop. Click on the "Authorize" button and check the console.

### Expected behavior
When the user clicks the login button (using TeamsFx.login([scope])), a popup should come up for the user to either login and/or consent to permissions.

### Additional context
This works well in Teams Desktop and web versions for Teams, Office and Outlook.

**Comment by kuojianlu** [comment] 2022-12-05 18:22
@akanjimm Thank you for reporting this issue. This is a bug caused by Outlook desktop client and the related people are fixing it.

**Comment by akanjimm** [comment] 2022-12-13 08:05
Thanks @kuojianlu. Please when should we expect the fix to be done?

**Comment by kuojianlu** [comment] 2022-12-13 08:14
@akanjimm I am not sure the exact date. However, there is a **workaround**: adding "https://localhost" and "localhost" to `validDomains` field in `templates/appPackage/manifest.template.json`, then do provision or F5 again, and add the app in Teams again.
For example:
```
"validDomains": [
    "https://localhost",
    "localhost",
    "${{TAB_DOMAIN}}"
],
```

**Comment by akanjimm** [comment] 2022-12-13 10:18
Thanks @kuojianlu. I would try this out.

**Comment by kuojianlu** [comment] 2023-01-16 02:33
@akanjimm This bug has been fixed. You can have a try. Close this issue.

**Closed by kuojianlu** 2023-01-16 02:33 UTC
Labels: bug, upstream, TA:Infra
