### ISSUE TITLE
TeamsFx: Get current signed in users theme from Teams.

### ISSUE THREAD

**Issue by AASPLLC** [OfficeDev/TeamsFx#7796] opened 2023-02-15 18:40 UTC
**Is your feature request related to a problem? Please describe.**
It should be possible to program this SDK to get the current theme being used by users:
![image](https://user-images.githubusercontent.com/123201739/219121513-e3056254-1881-4612-8cbf-33a62d1d4900.png)

Just looking for a way to grab the current theme being used by Teams already. We shouldn't need to re-invent the wheel on this one.
Why not make it possible to do something like TeamsFx.CurrentTheme.BackgroundColor, TeamsFx.CurrentTheme.TextStyles[], TeamsFx.CurrentTheme.SidePanelColor etc. It shouldn't be so overly complicated?

**Describe alternatives you've considered**
People have directed me to many other sources to try to build a theme, but that isn't the issue or the answer I am looking for.

**Comment by AASPLLC** [comment] 2023-02-15 18:41
oh, for reference I am using Blazor / C#.

**Comment by wrharper-AASP** [comment] 2023-02-23 13:31
I have written my own theme manager that has full customization and mimicked Teams themes to work around this issue for now, so this isn't critical. These recommendations add lots of bloated information into memory: https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/design/design-teams-app-ui-templates This feature should be able to be implemented without adding hardly anything that isn't in memory already since the Teams theme is already loaded.

**Comment by summzhan** [comment] 2023-02-27 11:36
> I have written my own theme manager that has full customization and mimicked Teams themes to work around this issue for now, so this isn't critical. These recommendations add lots of bloated information into memory: https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/design/design-teams-app-ui-templates This feature should be able to be implemented without adding hardly anything that isn't in memory already since the Teams theme is already loaded.
------------------------------------------------------------------------
Thanks for reaching out to provide the feature idea! we will take it as serious consideration to add get Teams Themes related SDKs. While at current stage we need more investigations on the feature priorities compared to our backlogs. We will keep you updated once we have decision! Thanks again!

**Comment by Alok-Singh-ops** [comment] 2023-08-26 07:04
@AASPLLC there is already a function provided my teams js. app.getContext() which gives us the current theme. and a method called registerOnthemeChange to monitor the theme change in ms teams application

**Comment by wrharper-AASP** [comment] 2023-09-21 20:49
I have written my own when ended up being better and more powerful than Teams anyway. Can you guys close this?

**Comment by adashen** [comment] 2023-09-27 06:41
Close as the issue is resolved.

**Closed by adashen** 2023-09-27 06:41 UTC
Labels: feature-request, TA:PM, needs attention
