### ISSUE TITLE
Microsoft Teams Apps: Issue using media permissions for tabs

### ISSUE THREAD

**Issue by Hector-Mina-98** [OfficeDev/TeamsFx#2888] opened 2021-11-08 15:40 UTC
According to the documentation
(https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/mobile-camera-image-permissions?view=msteams-client-js-latest)
If my Tab needs to use the microphone, I need to add this property to the manifest.json:
```
"devicePermissions": [ 
    "media",
 ],
```
It works fine when I open my tab inside the main window of Microsoft Teams
![image](https://user-images.githubusercontent.com/62456090/140770782-129ff844-898f-46cb-9be2-1b57826f9e53.png)

But, when I open my tab in a different window (popout), I don't get the message to grant that permission
![image](https://user-images.githubusercontent.com/62456090/140771075-ccbffa61-538d-454d-bc4d-bf7e44937490.png)

And my Tab will not able to use the microphone.
I also tried to grant that permission before open my app in a different window, but it doesn't work neither.

Aditional information:
Teams for Desktop (Version 1.4.00.29473)
SO: Windows 10

**Comment by asnow003** [comment] 2021-11-09 16:28
Hello there.. can you explain what you mean by popping out another window?  The device permissions only works while you are within Teams and not opening in others browser windows if you do a popout.

**Comment by Hector-Mina-98** [comment] 2021-11-09 18:10
Hello, Here is a gif showing a short example:
[https://drive.google.com/file/d/1ju01uctBwqMjfGsBG0M5KHMRQmxoJJ2V/view?usp=sharing](https://drive.google.com/file/d/1ju01uctBwqMjfGsBG0M5KHMRQmxoJJ2V/view?usp=sharing)

When I open my Tab, i can see the option to grant the permission, **but** when i select the button (shown in the following image), I can't grant the permissions for that window:
![image](https://user-images.githubusercontent.com/62456090/140979400-22a0865b-ecb2-4186-883e-b34f683ed2e0.png)

As you can see in the image, the tab is open in a different window that belongs to Microsoft Teams, it is not from a browser.

**Comment by asnow003** [comment] 2021-11-09 18:13
Oh I see... a Teams popout.  Let me see if I can get someone from that team to help out.

**Comment by asnow003** [comment] 2021-11-09 18:20
I reached out to the team and its a known issue they are working on.  Sorry it might be a little bit of time before it reaches the public.  Maybe a few months...  Thank you for your patience.

**Comment by Hector-Mina-98** [comment] 2021-11-09 18:38
Okay, thank you for the information.

**Comment by adashen** [comment] 2022-03-25 05:27
@Niranjan-S  Do you know whether the problem is fixed now?

**Comment by Prasad-MSFT** [comment] 2022-07-15 07:40
@adashen - This issue seems to be persist. We are checking with engineering team when this is going to be fixed and rolled out. We will inform you once we get further update. Thanks!

**Comment by Prasad-MSFT** [comment] 2022-08-10 10:31
@adashen - Currently, Teams doesn't support device permissions in pop out chat window, tabs, and the meeting side panel.

Ref: https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/media-capabilities?tabs=mobile#advantages

**Comment by Prasad-MSFT** [comment] 2022-08-11 07:45
We are closing the issue for now. Please feel free to reopen if required.

**Closed** 2023-01-03 05:06 UTC
Labels: upstream
