### ISSUE TITLE
bug report: Ext.UnknwonError

### ISSUE THREAD

**Issue by MuyangAmigo** [OfficeDev/TeamsFx#2322] opened 2021-09-15 04:21 UTC
Cannot read property 'isErr' of undefined

stack:
UnknwonError: Cannot read property 'isErr' of undefined
	at Object.returnSystemError (<REDACTED: user-file-path>:2:4615425)
	at wrapError (<REDACTED: user-file-path>:8:3592806)
	at <REDACTED: user-file-path>:8:3590994
	at Generator.next (<anonymous>)
	at fulfilled (<REDACTED: user-file-path>:8:3585345)

**Comment by MuyangAmigo** [comment] 2021-09-15 04:22
Complete Output Log:

[2021-09-15T04:19:55.654Z] [Info] - Teams Toolkit extension is now active!
[2021-09-15T04:19:55.709Z] [Info] - [core] start task:getProjectConfig, inputs:{"projectPath":"c:\\Users\\junjieli\\Development\\Test222","platform":"vsc","vscodeEnv":"local","function-dotnet-checker-enabled":{},"ignoreEnvInfo":true}
[2021-09-15T04:20:09.983Z] [Info] - [core] finish task:getProjectConfig
[2021-09-15T04:20:17.851Z] [Info] - [core] start task:getProjectConfig, inputs:{"projectPath":"c:\\Users\\junjieli\\Development\\Test222","platform":"vsc","vscodeEnv":"local","function-dotnet-checker-enabled":{},"ignoreEnvInfo":true}
[2021-09-15T04:20:17.863Z] [Info] - [core] finish task:getProjectConfig
[2021-09-15T04:20:55.281Z] [Info] - [core] start task:createProject, inputs:{"projectPath":"c:\\Users\\junjieli\\Development\\Test222","platform":"vsc","vscodeEnv":"local","function-dotnet-checker-enabled":{},"stage":"create"}
[2021-09-15T04:20:55.284Z] [Debug] - [core] success to get questions for createProject
[2021-09-15T04:21:12.983Z] [Info] - [core] success to run question model for createProject, answers:{"projectPath":"c:\\Users\\junjieli\\Development\\Test222","platform":"vsc","vscodeEnv":"local","function-dotnet-checker-enabled":{},"stage":"create","scratch":"yes","solution":"fx-solution-azure","capabilities":["Tab"],"host-type":"SPFx","spfx-framework-type":"react","spfx-webpart-name":"helloworld","spfx-webpart-desp":"helloworld description","programming-language":"typescript","folder":"c:\\Users\\junjieli\\Development","app-name":"junjieli0915","bot-password":"******"}
[2021-09-15T04:21:12.993Z] [Info] - [Teams Toolkit] Execute preTask summary-------------------------
[2021-09-15T04:21:12.993Z] [Info] - [Teams Toolkit] preTask overall result......................[ok]
[2021-09-15T04:21:13.032Z] [Info] - [Teams Toolkit] Execute Task summary----------------------------
[2021-09-15T04:21:13.032Z] [Info] - fx-resource-local-debug.scaffold............................ [ok]
[2021-09-15T04:21:13.032Z] [Info] - fx-resource-appstudio.scaffold.............................. [ok]
[2021-09-15T04:21:13.032Z] [Info] - [Teams Toolkit] Task overall result.........................[ok]
[2021-09-15T04:21:13.317Z] [Info] - [Teams Toolkit] Execute postTask summary------------------------
[2021-09-15T04:21:13.317Z] [Info] - fx-resource-spfx.postScaffold............................... [ok]
[2021-09-15T04:21:13.317Z] [Info] - [Teams Toolkit] postTask overall result.....................[ok]
[2021-09-15T04:21:13.352Z] [Debug] - [core] persist dev env profile to path c:\Users\junjieli\Development\junjieli0915\.fx\configs\config.dev.json: {"$schema":"https://raw.githubusercontent.com/OfficeDev/TeamsFx/dev/packages/api/src/schemas/envConfig.json","azure":{},"manifest":{"description":"You can customize the 'values' object to customize Teams app manifest for different environments. Visit https://aka.ms/teamsfx-config to learn more about this.","values":{}}}
[2021-09-15T04:21:13.355Z] [Info] - [Teams Toolkit] c:\Users\junjieli\Development\junjieli0915\.fx\configs\azure.parameters.dev.json does not exist. Generate it using c:\Users\junjieli\Development\junjieli0915\templates\azure\parameters.template.json.
[2021-09-15T04:21:13.356Z] [Info] - [core] finish task:createProject
[2021-09-15T04:21:13.362Z] [Error] - code:Ext.UnknwonError, message: Cannot read property 'isErr' of undefined, stack: UnknwonError: Cannot read property 'isErr' of undefined
	at Object.returnSystemError (c:\Users\junjieli\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-2.6.0\out\src\extension.js:2:4615425)
	at wrapError (c:\Users\junjieli\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-2.6.0\out\src\extension.js:8:3592806)
	at c:\Users\junjieli\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-2.6.0\out\src\extension.js:8:3590994
	at Generator.next (<anonymous>)
	at fulfilled (c:\Users\junjieli\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-2.6.0\out\src\extension.js:8:3585345)

**Comment by qinezh** [comment] 2021-09-16 07:11
The issue should be fixed in latest daily release: https://github.com/OfficeDev/TeamsFx/releases/tag/vscode-extension-2.6.1-alpha.eae7a7a8.0

@MuyangAmigo would you please have a try with above release? The root cause of this issue is that the integration with SPFx for multi-env support hasn't been started for the stable version V2.6.0.

**Closed** 2021-09-17 06:26 UTC
Labels: TA:Auth, TA:Infra
