### ISSUE TITLE
OnlineMeetingArtifact.Read.All not listed in permissions.json

### ISSUE THREAD

**Issue by stijndeschuymer** [OfficeDev/TeamsFx#4514] opened 2022-04-03 06:35 UTC
`OnlineMeetingArtifact.Read.All` as referenced here: https://docs.microsoft.com/en-us/graph/api/meetingattendancereport-list?view=graph-rest-1.0&tabs=http
seems to be not listed in the following file, resulting in an error when adding the permission to `permissions.json` of an app scaffolded with the Teams Toolkit Vs Code extension.
https://github.com/OfficeDev/TeamsFx/blob/444739e1734c88e16d74212fc783f382d4a7844b/packages/fx-core/src/plugins/resource/aad/permissions/permissions.json

**Comment by SLdragon** [comment] 2022-04-07 02:28
Thank you @stijndeschuymer  for reporting this issue.
Seems `OnlineMeetingArtifact.Read.All` is a newly added permission and not include in our `permissions.json` map file, we will update this file in the future release.

Our extension not only support permission name but also support permission id, so to workaround this issue, you can use permission id instead of permission name:

1. In your teams project root folder, you can find the `permissions.json` file, and it look like as below:
```
[
    {
        "resource": "Microsoft Graph",
        "delegated": [
            "User.Read"
        ],
        "application": []
    }
]
```

2. You can go to Azure portal to find the id of the permission
![image](https://user-images.githubusercontent.com/5545529/162107942-d4696572-da52-4a13-921a-9d7dad063440.png)

3. Update your permission in `permissions.json` file:
```
[
    {
        "resource": "Microsoft Graph",
        "delegated": [
            "User.Read",
            "110e5abb-a10c-4b59-8b55-9b4daa4ef743"
        ],
        "application": []
    }
]
```

**Comment by stijndeschuymer** [comment] 2022-04-11 08:02
Thanks for the workaround, using the Id works!

**Comment by adashen** [comment] 2022-04-13 06:15
Close as the issue is resolved close it now.

**Closed by adashen** 2022-04-13 06:15 UTC
Labels: investigating, TA:Auth
