### ISSUE TITLE
Ngrok issue: Failed to update message endpoint with https://7df3-103-99-202-239.ngrok.io/api/messagesDetailed

### ISSUE THREAD

**Issue by arielpriya** [OfficeDev/TeamsFx#5728] opened 2022-08-05 13:24 UTC
I am not able to re-run my bot project on VS code, I am getting error ---- "[Error] - code:BT.MessageEndpointUpdatingError, message: Failed to update message endpoint with https://1005-103-99-202-239.ngrok.io/api/messages Suggestions: Please check log in output channel and try to fix this issue. Please retry the current step" as I have updated the ngrok url to debug the code locally. 
https://prnt.sc/YVV7EUdVBH2F

**Comment by IvanJobs** [comment] 2022-08-11 08:45
@arielpriya Hi, Thanks for reaching out. Sorry for the inconvenience, we're actively investigating this issue, and will come back soon~

**Comment by IvanJobs** [comment] 2022-08-15 01:21
@arielpriya Hi, we received feedbacks from another customer who may meet the similar issue, but we cannot reproduce it as **it may be related to some intermediate status issue** in server side API. 

To get detailed messages of this error, we **added an improvement in daily version** [https://github.com/OfficeDev/TeamsFx/releases/download/vscode-extension-4.0.5-alpha.cfe223dbc.0/ms-teams-vscode-extension-4.0.5-alpha.cfe223dbc.0.vsix](daily build) to **print the detailed error messages of the API call** and can you help installing it, and **try again to check** the error messages?

**Comment by ChetanSharma-msft** [comment] 2022-08-18 10:16
Hello @arielpriya - Did you get chance to try the above suggested steps ?

**Comment by IvanJobs** [comment] 2022-08-25 06:02
@XVincentX  @arielpriya Hi, another possible reason is the remote bot registration was deleted somehow, so when Teams Toolkit was trying to update the message endpoint, 500 errors kept throwing out.
Can you help check if you can find the target bot registration on:
1. https://dev.botframework.com
2. https://dev.teams.microsoft.com/home
with the same M365 account used in Teams Toolkit? Thanks~

**Comment by IvanJobs** [comment] 2022-09-06 02:10
@XVincentX We're improving this part to provide a better developer experience, great thanks for your feedbacks.
As the facing issue was fixed, if no other things, the issue is supposed to be closed soon.

**Comment by IvanJobs** [comment] 2022-09-06 02:12
@XVincentX We're improving this part to provide a better developer experience, great thanks for your feedbacks.
As your facing issue was fixed, the issue is supposed to be closed soon.

**Comment by IvanJobs** [comment] 2022-09-07 03:26
Close this issue since it was fixed.

**Closed by IvanJobs** 2022-09-07 03:26 UTC
Labels: TA:Compute
